---
title: "BMvisualizing"
author: "Nils Wergeland"
format: html
execute: 
  message: false
  warning: false
format: 
  html:
    code-fold: true
---
###Loading libraries
```{r Loading Libraries}
library(dplyr)
library(Seurat)
library(patchwork)
library(Matrix)
library(ggplot2)
library(hdf5r)
library(SeuratData)
library(ggrepel)
library(tidyverse)
library(readxl)
library(ComplexHeatmap)
library(colorRamp2)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(VennDiagram)
library(MAST)
library(qvalue)
library(SingleCellExperiment)
library(monocle3)
library(SeuratWrappers)
```

###Loading objects
```{r Loading Objects}
#Setting working directory
setwd("~/Forskning/Neuroblastoma Met/BM Publication/")

#Loading objects
UnintegratedMerged <-readRDS("Från Gustav/Doublet-Removed Merged BM Object.rds")
IntegratedObject <- readRDS("Från Gustav/Integrated Seurat Object.rds")
MetaData <- readRDS("Från Gustav/Seurat Object Metadata.rds")

#Loading DE results
MastResult <- readRDS("Från Gustav/MAST Random Intercept Result.rds")
EdgeRResult <- readRDS("Från Gustav/Edge R Result.rds")
```

```{r Setting colors}
# Set PDX colours
  PDX_colours <- setNames(c("#295692","#d09e53","#529fa6"), nm = sprintf("PDX%d",1:3))
  PDX_colours_light <- setNames(colorspace::lighten(PDX_colours,amount = 0.3), nm = sprintf("PDX%d",1:3))
  PDX_colours_dark <- setNames(colorspace::darken(PDX_colours,amount = 0.3), nm = sprintf("PDX%d",1:3))
# View colours
  all_colours <- c(PDX_colours_light,PDX_colours,PDX_colours_dark)
  all_colours <- all_colours[order(names(all_colours))]
  colorspace::demoplot(all_colours,type = "bar")
  
  # Import table
  dataset_information <- read_excel("~/Forskning/Neuroblastoma Met/T10/Raw Files/Deducing Dataset Names.xlsx")
# Make certain columns factor
  dataset_information <- dataset_information %>%
    mutate_at(vars(`Include in Analysis`, Folder, `Raw Matrix`, Original, `Presumed Cell Line`, `Mouse #`, Series, `Presumed Tissue`),
              as.factor) %>%
    arrange(Folder,`Current Folder Name`)
# Filter the dataset
  included_dataset_information <- dataset_information %>% 
    filter(`Include in Analysis` == "Yes")
  
  sample_indices <- 1:15
  
  # Create metadata table
  metadata_to_add <- included_dataset_information[sample_indices,] %>% 
    select(`Seurat Object Name`,Folder,`Year Sequenced`,`Presumed Run`,`Current Folder Name`,Series,`Presumed Cell Line`,
           `Presumed Tissue`,`Mouse #`) %>% 
    mutate(`Seurat Object Name` = gsub("_Counts$", "", `Seurat Object Name`)) %>%
    dplyr::rename(Cell_Line = `Presumed Cell Line`,
                  Mouse_n = `Mouse #`,
                  Tissue = `Presumed Tissue`) %>%
    mutate(Cell_Line_n = case_when(
      Cell_Line == "PALLAD" ~ "PDX1",
      Cell_Line == "FORPA" ~ "PDX2",
      Cell_Line == "LUNOV" ~ "PDX3",
      TRUE ~ NA_character_
    )) %>% 
    mutate(Mouse_n = paste0(Series,"-",Cell_Line_n,"-",Mouse_n)) %>% 
    mutate(Cell_Line_n = factor(x = Cell_Line_n,levels = c("PDX1", "PDX2", "PDX3")),
           Tissue = relevel(Tissue, ref = "PT") ) %>% 
    relocate(Cell_Line_n, .after = Cell_Line)
# Generate sorted mouse ID string
  mouse_ID_sorted <- unique(metadata_to_add %>% arrange(Cell_Line_n,Series,Mouse_n) %>% pull(Mouse_n) )
# Make mouse ID factors
  metadata_to_add <- metadata_to_add %>% mutate(Mouse_n = factor(x = Mouse_n, levels = mouse_ID_sorted))
  
# Create a vector to track how many times each PDX line appears
  colour_use_count <- table(metadata_to_add$Cell_Line_n)
# Generate the color palette vector using sapply
  PDX_dataset_colours <- unlist(sapply(names(colour_use_count), function(i) {
    if (colour_use_count[i] > 1) {
      colorRampPalette(c(PDX_colours_dark[i], PDX_colours[i], PDX_colours_light[i]))(colour_use_count[i])
    } else {
      NULL
    }
  }))
  names(PDX_dataset_colours) <- metadata_to_add$`Seurat Object Name`[order(metadata_to_add$Cell_Line_n)]
# View the palette
  pie_colours <- function(colours) pie(rep(1, length(colours)), col = colours, labels = names(colours))
  pie_colours(PDX_dataset_colours)

  Tissue_colours <- setNames(scales::hue_pal()(2), nm = rev(levels(IntegratedObject@meta.data$Tissue) ) )

  
#Setting Colors manually
PDX_colours <- c("LU-NB-1" = "#295692", "LU-NB-2" = "#d09e53", "LU-NB-3" = "#529fa6")
  
#Cluster colors, MetBrewer - Signac
Cluster_colours <- c("1" = "#F4C40FFF", "2" = "#FE9B00FF", "3" = "#D8443CFF", "4" = "#9B3441FF", "5" = "#DE597CFF", "6" = "#E87B89FF","7" = "#E6A2A6FF", "8" = "#AA7AA1FF", "9" = "#9F5691FF", "10" = "#633372FF", "11" = "#1F6E9CFF", "12" = "#2B9B81FF", "13" = "#92C051FF")

#Function that saves plots, from Gustav
saveplots <- function(object,location,filename,w = 900,h = 900,pointsize = 12,res = 150){
  setwd("~/Forskning/Neuroblastoma Met/BM Publication/")
  png(paste0(location,filename,".png"),width = w, height = h, units = "px", pointsize = pointsize, res = res)
  print(object)
  dev.off()
  ggsave(path = location,filename = paste0(filename,".eps"), plot = object,width = w,height = h,dpi = res, units = "px")
}
```

###Visualizing Data
```{r Volcplot MAST}
#Data frame with gene name, log2-fold change and adjusted p-value for MAST results, with significance if in MastUp or MastDown
MastDF <- data.frame(Gene = MastResult$primerid, Log2FC = MastResult$coef, AdjPValue = MastResult$`Pr(>Chisq)`, Significant = ifelse(MastResult$`Pr(>Chisq)` < 0.05 & MastResult$coef > 0.25, "Upregulated", ifelse(MastResult$`Pr(>Chisq)` < 0.05 & MastResult$coef < -0.25, "Downregulated", "Not Significant")))

#List of genes with adjusted p-value < 0.01 and log2-fold change > 2
MastUp <- MastDF %>% filter(AdjPValue < 0.05 & Log2FC > 0.25) %>% pull(Gene)
#List of genes with adjusted p-value < 0.01 and log2-fold change < -2
MastDown <- MastDF %>% filter(AdjPValue < 0.05 & Log2FC < -0.25) %>% pull(Gene)

top_genes <- MastDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

#Volcano plot for MAST results, lines for significance borders and label and colors for significant genes
ggplot(MastDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point() +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_text_repel(data = MastDF %>% filter(Significant != "Not Significant"), aes(label = Gene), size = 3)

VolcanoplotMast <- ggplot(MastDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#6BAED6", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#E6550D")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "PT-BM: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMast, "../BM Publication/", "Volcanoplot Mast results")
svg("Volcanoplot Mast results.svg")
VolcanoplotMast
dev.off()
VolcanoplotMast
```

```{r Volcplot EdgeR}
#Dataframe with gene name, log2-fold change and adjusted p-value for EdgeR results, with significance if in EdgeRUp or EdgeRDown
EdgeRDF <- data.frame(Gene = EdgeRResult$Gene, Log2FC = EdgeRResult$avg_log2FC, AdjPValue = EdgeRResult$p_val, Significant = ifelse(EdgeRResult$p_val < 0.01 & EdgeRResult$avg_log2FC > 1, "Upregulated", ifelse(EdgeRResult$p_val < 0.01 & EdgeRResult$avg_log2FC < -1, "Downregulated", "Not Significant")))

#List of upregulated genes in EdgeRobject
EdgeRUp <- EdgeRDF %>% filter(AdjPValue < 0.01 & Log2FC > 1) %>% pull(Gene)
#List of downregulated genes in EdgeR object
EdgeRDown <- EdgeRDF %>% filter(AdjPValue < 0.01 & Log2FC < -1) %>% pull(Gene)

#Volcano plot for EdgeR results, lines for significance borders and label and colors for significant genes
ggplot(EdgeRDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point() +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.01), linetype = "dashed") +
  geom_text_repel(data = EdgeRDF %>% filter(Significant != "Not Significant"), aes(label = Gene), size = 3)

```

```{r Size of groups}
#Changing PDX_ to LU-NB-_
IntegratedObject$Cell_Line_n <- as.character(IntegratedObject$Cell_Line_n)
IntegratedObject$Cell_Line_n[IntegratedObject$Cell_Line_n == "PDX1"] <- "LU-NB-1"
IntegratedObject$Cell_Line_n[IntegratedObject$Cell_Line_n == "PDX2"] <- "LU-NB-2"
IntegratedObject$Cell_Line_n[IntegratedObject$Cell_Line_n == "PDX3"] <- "LU-NB-3"
IntegratedObject$Cell_Line_n <- as.factor(IntegratedObject$Cell_Line_n)


#Adding grouped metadata for easier plotting
IntegratedObject$Cell_Line_n_Tissue <- paste(IntegratedObject$Cell_Line_n, IntegratedObject$Tissue, sep = "_")
IntegratedObject$Mouse_n_Tissue <- paste(IntegratedObject$Mouse_n, IntegratedObject$Tissue, sep = "_")

#Checking group sizes
table(IntegratedObject$Tissue)
table(IntegratedObject$Cell_Line_n_Tissue)
table(IntegratedObject$Mouse_n_Tissue)
```


```{r Visualizing the integration}
#Runing UMAP on integrated data
IntegratedObject <- RunUMAP(IntegratedObject, reduction.name = "umap.harmony", reduction = "integrated.harmony", dims = 1:30, verbose = FALSE, seed.use = 1999)
IntegratedObject <- RunUMAP(IntegratedObject, reduction.name = "umap.cca", reduction = "integrated.cca", dims = 1:30, verbose = FALSE, seed.use = 1999)


wrap_plots(
  DimPlot(IntegratedObject, reduction = "umap.cca", group.by = "Cell_Line_n", cols = PDX_colours) + ggtitle("CCA Integrated Object"),
  DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Cell_Line_n", cols = PDX_colours) + ggtitle("Harmony Integrated Object"),
  DimPlot(IntegratedObject, reduction = "umap.merged", group.by = "Cell_Line_n", cols = PDX_colours) + ggtitle("non-integrated Merged Object"),
  DimPlot(IntegratedObject, reduction = "umap.cca", group.by = "Tissue", cols = Tissue_colours) + ggtitle("CCA Integrated Object"),
  DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("Harmony Integrated Object"),
  DimPlot(IntegratedObject, reduction = "umap.merged", group.by = "Tissue", cols = Tissue_colours) + ggtitle("non-integrated Merged Object"),
  ncol = 3
)
```

```{r Visualizing Object}
DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Tissue", split.by = "Mouse_n", ncol = 3, cols = Tissue_colours)
DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Tissue", split.by = "Cell_Line_n", ncol = 3, cols = Tissue_colours)
DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Mouse_n", split.by = "Cell_Line_n", ncol = 3)

#Use same colors for PDX as Gustav
Figure1 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Cell_Line_n", cols = PDX_colours) + ggtitle("Grouped by Cell Line") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
Figure1

saveRDS(Figure1, "Figure1.rds")

#Factoring Levels
IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"))

#Add colors, PDX specific for title and dots for Site
DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Tissue", split.by = "Cell_Line_n_Tissue", ncol = 3, cols = Tissue_colours) + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = "black")) + ylab("UMAP_2") + xlab("UMAP_1")


PT1plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-1_PT"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("PT LU-NB-1") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[1])) + ylab("UMAP 2")
PT2plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-2_PT"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("PT LU-NB-2") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[2]))
PT3plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-3_PT"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("PT LU-NB-3") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[3]))
BM1plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-1_BM"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("BM LU-NB-1") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[1])) + ylab("UMAP 2") + xlab("UMAP 1")
BM2plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-2_BM"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("BM LU-NB-2") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.y = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[2])) + xlab("UMAP 1")
BM3plot <- DimPlot(IntegratedObject, cells = WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-3_BM"), reduction = "umap.harmony", group.by = "Tissue", cols = Tissue_colours) + ggtitle("BM LU-NB-3") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.y = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[3])) + xlab("UMAP 1")
Figure2 <- wrap_plots(PT1plot, PT2plot, PT3plot, BM1plot, BM2plot, BM3plot, ncol = 3) + ylab("UMAP_2") + xlab("UMAP_1")
Figure2
```

###Finding Clusters
```{r Clustering With different resolutions}
#Clustering with res 0.9
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.9)
#ClustRes09 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.9")

#0.8
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.8)
#ClustRes08 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.8")

#0.7
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.7)
#ClustRes07 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.7")

#0.6
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.6)
#ClustRes06 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.6")

#0.5
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.5)
#ClustRes05 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.5")

#0.4
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.4)
#ClustRes04 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.4")

#0.3
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.3)
#ClustRes03 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.3")

#0.2
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.2)
#ClustRes02 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.2")

##0.1
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.1)
#ClustRes01 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.1")

#Visualizing clusters with different resolutions
#wrap_plots(
#  ClustRes09, ClustRes08, ClustRes07, ClustRes06, ClustRes05, ClustRes04, ClustRes03, ClustRes02, #ClustRes01,
#  ncol = 3
#)
```

```{r Finding clusters with smaller resolutions}
#Finding clusters with smaller resolutions
#0.2
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.2)
#ClustRes20 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.2")

#0.18
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.18)
#ClustRes18 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.18")

#0.16
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.16)
#ClustRes16 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.16")

#0.14
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.14)
#ClustRes14 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.14")

#0.12
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.12)
#ClustRes12 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.12")

#0.10
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.10)
#ClustRes10 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.10")

#0.08
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.08)
#ClustRes08 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.08")

#0.06
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.06)
#ClustRes06 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.06")

#0.04
#IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.04)
#ClustRes04 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters") + #ggtitle("Resolution 0.04")

#Visualizing clusters with different resolutions
#wrap_plots(
#  ClustRes20, ClustRes18, ClustRes16, ClustRes14, ClustRes12, ClustRes10, ClustRes08, ClustRes06, #ClustRes04,
#  ncol = 3
#)

```

```{r Nbr of clusters at different resolutions}
#Tar tid och redan kört, behöver ej köras om
#resList <- list()
##loop from 0.01 to 1.0 with 0.01 increments
#for (res in seq(0.01, 1.0, by = 0.01)) {
#  #Find neighbors and clusters
#  IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
#  IntegratedObject <- FindClusters(IntegratedObject, resolution = res)
#  
#  #Count number of clusters
#  clustnbr <- length(unique(IntegratedObject$seurat_clusters))
#  
#  #Add number of clusters to list
#  resList[[as.character(res)]] <- clustnbr
#}

#saveRDS(resList, "Number of clusters at different resolutions.rds")
#resList <- readRDS("Number of clusters at different resolutions.rds")

#Ggplot of changes in cluster number with different resolutions
#resDF <- data.frame(Resolution = as.numeric(names(resList)), ClusterNumber = unlist(resList))
#ggplot(resDF, aes(x = Resolution, y = ClusterNumber)) +
#  geom_line() +
#  geom_point() +
#  ggtitle("Number of Clusters at Different Resolutions") +
#  xlab("Resolution") +
#  ylab("Number of Clusters") +
#  theme_minimal()
```

```{r Setting resolution, watching results}
#13 cluster at res 0.15 seem to be a good choice
IntegratedObject <- FindNeighbors(IntegratedObject, reduction = "integrated.harmony", dims = 1:30)
IntegratedObject <- FindClusters(IntegratedObject, resolution = 0.15)

#Setting cluster names 1-13
new.cluster.ids <- c(1:13) 
names(new.cluster.ids) <- levels(IntegratedObject)
IntegratedObject <- RenameIdents(IntegratedObject, new.cluster.ids)
IntegratedObject$seurat_clusters <- Idents(IntegratedObject)

Figure3 <- DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "seurat_clusters", cols = Cluster_colours) + ggtitle("Resolution 0.15") + ggtitle("Clustered") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
Figure3
DimPlot(IntegratedObject, reduction = "umap.harmony", group.by = "Cell_Line_n", split.by = "seurat_clusters", ncol = 5, cols = PDX_colours) + ggtitle("Resolution 0.15")
```


###Investigate clusters
```{r Composition of clusters}
#Dataframe of each Cell_Line_n_Tissue composition of clusters by creating 3 vectors and combining
PDXandSite <- rep(c("LU-NB-1_PT", "LU-NB-1_BM", "LU-NB-2_PT", "LU-NB-2_BM", "LU-NB-3_PT", "LU-NB-3_BM"), each = 13)
Clusters <- rep(c(1:13), times = 6)
PT1comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-1_PT"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-1_PT"))
  PT1comp <- c(PT1comp, comp)
}
PT2comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-2_PT"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-2_PT"))
  PT2comp <- c(PT2comp, comp)
}
PT3comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-3_PT"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-3_PT"))
  PT3comp <- c(PT3comp, comp)
}
BM1comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-1_BM"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-1_BM"))
  BM1comp <- c(BM1comp, comp)
}
BM2comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-2_BM"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-2_BM"))
  BM2comp <- c(BM2comp, comp)
}
BM3comp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Cell_Line_n_Tissue == "LU-NB-3_BM"))/length(WhichCells(IntegratedObject, expression = Cell_Line_n_Tissue == "LU-NB-3_BM"))
  BM3comp <- c(BM3comp, comp)
}
CellLineTissueCompDF <- data.frame(PDX_Site <- PDXandSite, Cluster = Clusters, Percentage = c(PT1comp, BM1comp, PT2comp, BM2comp, PT3comp, BM3comp))
CellLineTissueCompDF$Cluster <- factor(CellLineTissueCompDF$Cluster, levels = 1:13)
CellLineTissueCompDF$PDX_Site <- factor(CellLineTissueCompDF$PDX_Site, levels = c("LU-NB-1_PT", "LU-NB-1_BM", "LU-NB-2_PT", "LU-NB-2_BM", "LU-NB-3_PT", "LU-NB-3_BM"))

#Barplot
Figure4 <- ggplot(CellLineTissueCompDF, aes(fill=Cluster, y=Percentage, x=PDX_Site, size=8)) + 
  geom_bar(position = "fill", stat = "identity", width = 0.9) + 
  ggtitle("Percentage of Clusters per PDX and Location") +
  scale_fill_manual(values = Cluster_colours) +
  scale_y_continuous(labels = scales::label_percent(), expand = c(0, 0)) +
  scale_x_discrete(limits = c("LU-NB-1_PT", "LU-NB-1_BM", "", "LU-NB-2_PT", "LU-NB-2_BM", "", "LU-NB-3_PT", "LU-NB-3_BM"), labels = c("PT LU-NB-1", "BM LU-NB-1", "", "PT LU-NB-2", "BM LU-NB-2", "", "PT LU-NB-3", "BM LU-NB-3")) +
  geom_text(aes(label = ifelse(Percentage > 3, round(Percentage, 2), "")), 
            position = position_fill(vjust = 0.5), color =  "black", size = 4) +
  theme_minimal() +
  theme(
  legend.position = "right",
  legend.title = element_blank(),
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.y = element_blank(),
  axis.line.y = element_line(color = "black", linewidth = 1.5, lineend = "square"),
  axis.ticks.y = element_line(color = "black", linewidth = 1.5),
  axis.ticks.length.y = unit(0.2, "cm"),
  axis.line.x = element_blank(),
  axis.text.x = element_text(angle = 45, hjust = 1, size = 15, colour = c(PDX_colours[1], PDX_colours[1], PDX_colours[2], PDX_colours[2], PDX_colours[2], PDX_colours[3], PDX_colours[3])),
  axis.text.y = element_text(size = 15),
  panel.grid = element_blank(),
  text = element_text(size = 12, color = "black")
)
Figure4

#Barplot of all PT and BM composition of clusters
Site <- rep(c("PT", "BM"), each = 13)
Clusters <- rep(c(1:13), times = 2)
PTcomp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Tissue == "PT"))/length(WhichCells(IntegratedObject, expression = Tissue == "PT"))
  PTcomp <- c(PTcomp, comp)
}
BMcomp <- c()
for (cluster in 1:13) {
  comp = 100*length(WhichCells(IntegratedObject, idents = cluster, expression = Tissue == "BM"))/length(WhichCells(IntegratedObject, expression = Tissue == "BM"))
  BMcomp <- c(BMcomp, comp)
}
TissueCompDF <- data.frame(Site <- Site, Cluster = Clusters, Percentage = c(PTcomp, BMcomp))
TissueCompDF$Cluster <- factor(TissueCompDF$Cluster, levels = 1:13)
TissueCompDF$Site <- factor(TissueCompDF$Site, levels = c("PT", "BM"))

#Barplot
Figure7 <- ggplot(TissueCompDF, aes(fill=Cluster, y=Percentage, x=Site, size=8)) + 
  geom_bar(position = "fill", stat = "identity", width = 0.8) + 
  ggtitle("Percentage of Clusters per Site") +
  scale_fill_manual(values = Cluster_colours) +
  scale_y_continuous(labels = scales::label_percent(), expand = c(0, 0)) +
  scale_x_discrete(limits = c("PT", "BM"), labels = c("PT", "BM")) +
  geom_text(aes(label = ifelse(Percentage > 3, round(Percentage, 2), "")), 
            position = position_fill(vjust = 0.5), color =  "black", size = 4) +
  theme_minimal() +
  theme(
  legend.position = "right",
  legend.title = element_blank(),
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.y = element_blank(),
  axis.line.y = element_line(color = "black", linewidth = 1.5, lineend = "square"),
  axis.ticks.y = element_line(color = "black", linewidth = 1.5),
  axis.ticks.length.y = unit(0.2, "cm"),
  axis.line.x = element_blank(),
  axis.text.x = element_text(angle = 0, hjust = 0.5, size = 20, colour = c(Tissue_colours[1], Tissue_colours[2])),
  axis.text.y = element_text(size = 15),
  panel.grid = element_blank(),
  text = element_text(size = 12, color = "black")
)
Figure7
```

```{r Finding cluster markers}
#Finding markers on log-normalized data
IntegratedObject <- PrepSCTFindMarkers(IntegratedObject)
clusterMarkers <- FindAllMarkers(IntegratedObject, min.pct = 0.1, logfc.threshold = 0.25, only.pos = TRUE)

#Top 10 and top 5 per cluster
clusterMarkers %>% 
  group_by(cluster) %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  slice_head(n = 8) %>%
  ungroup() -> top10Cluster
top10Cluster <- unique(top10Cluster$gene)

clusterMarkers %>% 
  group_by(cluster) %>%
  dplyr::filter(p_val_adj < 0.05) %>%
  slice_head(n = 5) %>%
  ungroup() -> top5Cluster
top5Cluster <- unique(top5Cluster$gene)

```

```{r Heatmap of top 10 genes per cluster}
IntegratedObject <- ScaleData(IntegratedObject, assay = "SCT", features = top10Cluster)

#Heatmap cluster 1
Heatmap1 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "1")
Heatmap1Matr <- GetAssayData(Heatmap1, assay = "SCT", layer = "scale.data")
Heatmap1Matr <- Heatmap1Matr[order(factor(rownames(Heatmap1Matr), levels = top10Cluster)), ]
Heatmap1Annotation <- HeatmapAnnotation(Cluster = Heatmap1$seurat_clusters, PDX = Heatmap1$Cell_Line_n, Site = Heatmap1$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)
col_fun = colorRamp2(c(-2, 0, 2), c("#FF00FF", "#000000", "#FFFF00"))

h1 <- Heatmap(Heatmap1Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap1Annotation, col = col_fun, use_raster = FALSE, column_title = "1", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 2
Heatmap2 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "2")
Heatmap2Matr <- GetAssayData(Heatmap2, assay = "SCT", layer = "scale.data")
Heatmap2Matr <- Heatmap2Matr[order(factor(rownames(Heatmap2Matr), levels = top10Cluster)), ]
Heatmap2Annotation <- HeatmapAnnotation(Cluster = Heatmap2$seurat_clusters, PDX = Heatmap2$Cell_Line_n, Site = Heatmap2$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h2 <- Heatmap(Heatmap2Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap2Annotation, col = col_fun, use_raster = FALSE, column_title = "2", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 3
Heatmap3 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "3")
Heatmap3Matr <- GetAssayData(Heatmap3, assay = "SCT", layer = "scale.data")
Heatmap3Matr <- Heatmap3Matr[order(factor(rownames(Heatmap3Matr), levels = top10Cluster)), ]
Heatmap3Annotation <- HeatmapAnnotation(Cluster = Heatmap3$seurat_clusters, PDX = Heatmap3$Cell_Line_n, Site = Heatmap3$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h3 <- Heatmap(Heatmap3Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap3Annotation, col = col_fun, use_raster = FALSE, column_title = "3", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 4
Heatmap4 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "4")
Heatmap4Matr <- GetAssayData(Heatmap4, assay = "SCT", layer = "scale.data")
Heatmap4Matr <- Heatmap4Matr[order(factor(rownames(Heatmap4Matr), levels = top10Cluster)), ]
Heatmap4Annotation <- HeatmapAnnotation(Cluster = Heatmap4$seurat_clusters, PDX = Heatmap4$Cell_Line_n, Site = Heatmap4$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h4 <- Heatmap(Heatmap4Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap4Annotation, col = col_fun, use_raster = FALSE, column_title = "4", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 5
Heatmap5 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "5")
Heatmap5Matr <- GetAssayData(Heatmap5, assay = "SCT", layer = "scale.data")
Heatmap5Matr <- Heatmap5Matr[order(factor(rownames(Heatmap5Matr), levels = top10Cluster)), ]
Heatmap5Annotation <- HeatmapAnnotation(Cluster = Heatmap5$seurat_clusters, PDX = Heatmap5$Cell_Line_n, Site = Heatmap5$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h5 <- Heatmap(Heatmap5Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap5Annotation, col = col_fun, use_raster = FALSE, column_title = "5", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 6
Heatmap6 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "6")
Heatmap6Matr <- GetAssayData(Heatmap6, assay = "SCT", layer = "scale.data")
Heatmap6Matr <- Heatmap6Matr[order(factor(rownames(Heatmap6Matr), levels = top10Cluster)), ]
Heatmap6Annotation <- HeatmapAnnotation(Cluster = Heatmap6$seurat_clusters, PDX = Heatmap6$Cell_Line_n, Site = Heatmap6$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h6 <- Heatmap(Heatmap6Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap6Annotation, col = col_fun, use_raster = FALSE, column_title = "6", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 7
Heatmap7 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "7")
Heatmap7Matr <- GetAssayData(Heatmap7, assay = "SCT", layer = "scale.data")
Heatmap7Matr <- Heatmap7Matr[order(factor(rownames(Heatmap7Matr), levels = top10Cluster)), ]
Heatmap7Annotation <- HeatmapAnnotation(Cluster = Heatmap7$seurat_clusters, PDX = Heatmap7$Cell_Line_n, Site = Heatmap7$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h7 <- Heatmap(Heatmap7Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap7Annotation, col = col_fun, use_raster = FALSE, column_title = "7", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 8
Heatmap8 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "8")
Heatmap8Matr <- GetAssayData(Heatmap8, assay = "SCT", layer = "scale.data")
Heatmap8Matr <- Heatmap8Matr[order(factor(rownames(Heatmap8Matr), levels = top10Cluster)), ]
Heatmap8Annotation <- HeatmapAnnotation(Cluster = Heatmap8$seurat_clusters, PDX = Heatmap8$Cell_Line_n, Site = Heatmap8$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h8 <- Heatmap(Heatmap8Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap8Annotation, col = col_fun, use_raster = FALSE, column_title = "8", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Heatmap Cluster 9
Heatmap9 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "9")
Heatmap9Matr <- GetAssayData(Heatmap9, assay = "SCT", layer = "scale.data")
Heatmap9Matr <- Heatmap9Matr[order(factor(rownames(Heatmap9Matr), levels = top10Cluster)), ]
Heatmap9Annotation <- HeatmapAnnotation(Cluster = Heatmap9$seurat_clusters, PDX = Heatmap9$Cell_Line_n, Site = Heatmap9$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h9 <- Heatmap(Heatmap9Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap9Annotation, col = col_fun, use_raster = FALSE, column_title = "9", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6), width = unit(3, "mm"))

#Heatmap Cluster 10
Heatmap10 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "10")
Heatmap10Matr <- GetAssayData(Heatmap10, assay = "SCT", layer = "scale.data")
Heatmap10Matr <- Heatmap10Matr[order(factor(rownames(Heatmap10Matr), levels = top10Cluster)), ]
Heatmap10Annotation <- HeatmapAnnotation(Cluster = Heatmap10$seurat_clusters, PDX = Heatmap10$Cell_Line_n, Site = Heatmap10$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h10 <- Heatmap(Heatmap10Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap10Annotation, col = col_fun, use_raster = FALSE, column_title = "10", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6), width = unit(3, "mm"))

#Heatmap Cluster 11
Heatmap11 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "11")
Heatmap11Matr <- GetAssayData(Heatmap11, assay = "SCT", layer = "scale.data")
Heatmap11Matr <- Heatmap11Matr[order(factor(rownames(Heatmap11Matr), levels = top10Cluster)), ]
Heatmap11Annotation <- HeatmapAnnotation(Cluster = Heatmap11$seurat_clusters, PDX = Heatmap11$Cell_Line_n, Site = Heatmap11$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h11 <- Heatmap(Heatmap11Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap11Annotation, col = col_fun, use_raster = FALSE, column_title = "11", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6), width = unit(2, "mm"))

#Heatmap Cluster 12
Heatmap12 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "12")
Heatmap12Matr <- GetAssayData(Heatmap12, assay = "SCT", layer = "scale.data")
Heatmap12Matr <- Heatmap12Matr[order(factor(rownames(Heatmap12Matr), levels = top10Cluster)), ]
Heatmap12Annotation <- HeatmapAnnotation(Cluster = Heatmap12$seurat_clusters, PDX = Heatmap12$Cell_Line_n, Site = Heatmap12$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c(" ", " ", " "), show_legend = FALSE)

h12 <- Heatmap(Heatmap12Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap12Annotation, col = col_fun, use_raster = FALSE, column_title = "12", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6), width = unit(2, "mm"))

#Heatmap Cluster 13
Heatmap13 <- subset(IntegratedObject, features = top10Cluster, seurat_clusters == "13")
Heatmap13Matr <- GetAssayData(Heatmap13, assay = "SCT", layer = "scale.data")
Heatmap13Matr <- Heatmap13Matr[order(factor(rownames(Heatmap13Matr), levels = top10Cluster)), ]
Heatmap13Annotation <- HeatmapAnnotation(Cluster = Heatmap13$seurat_clusters, PDX = Heatmap13$Cell_Line_n, Site = Heatmap13$Tissue, col = list(Cluster = Cluster_colours, PDX = PDX_colours, Site = Tissue_colours), annotation_label = c("Cluster", "PDX", "Site"), show_legend = FALSE)

h13 <- Heatmap(Heatmap13Matr, name = "clusterHeatmap", cluster_rows = FALSE, cluster_columns = FALSE, show_column_dend = FALSE, show_column_names = FALSE, show_row_dend = FALSE , top_annotation = Heatmap13Annotation, col = col_fun, use_raster = FALSE, column_title = "13", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6), width = unit(2, "mm"))

#Preparing Legends
matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
clusterLGND <- Legend(at = 1:13, title = "Clusters", legend_gp = gpar(fill = Cluster_colours))
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
typeLGND <- Legend(labels = c("PT", "BM"), title = "Site", legend_gp = gpar(fill = Tissue_colours))
LGNDs <- packLegend(matrixLGND, clusterLGND, cellLineLGND, typeLGND)

#Printing it together
fullHTMap <- h1 + h2 + h3 + h4 + h5 + h6 + h7 + h8 + h9 + h10 + h11 + h12 + h13
Figure5 <- draw(fullHTMap, ht_gap = unit(1, "mm"), annotation_legend_list = LGNDs)

svg("Heatmap DEG.svg", width = 15, height = 8)
Figure5
dev.off()

```

```{r Dotplot of top 5 genes per cluster}
IntegratedObject$seurat_clusters <- factor(IntegratedObject$seurat_clusters, levels = 13:1)

Figure6 <- DotPlot(IntegratedObject, features = top5Cluster, group.by = "seurat_clusters") + RotatedAxis()
Figure6

IntegratedObject$seurat_clusters <- factor(IntegratedObject$seurat_clusters, levels = 1:13)
```

###Checking Mesenchymal and Adrenergic markers
```{r}
ADRNgenes <- c("TH", "DBH", "CHGA", "PHOX2B", "GATA3", "MYCN", "PHOX2A")
MESgenes <- c("CD44", "FN1", "COL1A1", "RUNX2", "WWTR1", "IRF1", "SNAI2", "VIM")

#Feature plots for ADRN and MES markers
FeaturePlot(IntegratedObject, features = ADRNgenes, reduction = "umap.harmony", ncol = 4, cols = c("lightgrey", "orange"))
FeaturePlot(IntegratedObject, features = MESgenes, reduction = "umap.harmony", ncol = 4, cols = c("lightgrey", "navy"))

#VlnPlot for ADRN and MES markers per cluster
VlnPlot(IntegratedObject, features = ADRNgenes, group.by = "seurat_clusters", ncol = 4, assay="RNA", layer="data", pt.size = 0) + ggtitle("ADRN Markers")
VlnPlot(IntegratedObject, features = MESgenes, group.by = "seurat_clusters", ncol = 4, assay="RNA", layer="data", pt.size = 0) + ggtitle("MES Markers")

#AddModuleScore for ADRN and MES
IntegratedObject <- AddModuleScore(IntegratedObject, features = list(ADRNgenes), name = "ADRN_Score", assay="RNA", layer="data")
IntegratedObject <- AddModuleScore(IntegratedObject, features = list(MESgenes), name = "MES_Score", assay="RNA", layer="data")
IntegratedObject$ADRNMESdiff <- scale(IntegratedObject$ADRN_Score1) - scale(IntegratedObject$MES_Score1)

#VlnPlot for ADRN and MES score per cluster
VlnAC <- VlnPlot(IntegratedObject, features = c("ADRN_Score1"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing") + ggtitle("ADRN Score")+ geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + ggpubr::stat_compare_means(method = "anova", label.y = max(IntegratedObject@meta.data$ADRN_Score1, na.rm = TRUE) * 0.95)
VlnMC <- VlnPlot(IntegratedObject, features = c("MES_Score1"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing") + ggtitle("MES Score") + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + ggpubr::stat_compare_means(method = "anova", label.y = max(IntegratedObject@meta.data$MES_Score1, na.rm = TRUE) * 0.95)
VlnDC <- VlnPlot(IntegratedObject, features = c("ADRNMESdiff"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing") + ggtitle("Adrn - Mes difference") + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + ggpubr::stat_compare_means(method = "anova", label.y = max(IntegratedObject@meta.data$ADRNMESdiff, na.rm = TRUE) * 0.95)

AdrnMesCluster <- wrap_plots(VlnAC, VlnMC, VlnDC, ncol = 3)

saveplots(AdrnMesCluster, "../BM Publication/",  "Vlnplot ADRN_MES_Score_Cluster", w = 3000)
svg("Vlnplot ADRN_MES_Score_Cluster.svg", width = 12)
AdrnMesCluster
dev.off()

FeatureplotAdrnMes <- FeaturePlot(IntegratedObject, features = c("ADRN_Score1", "MES_Score1"), reduction = "umap.harmony", min.cutoff = "q10", max.cutoff = "q90", blend = TRUE, cols = c("lightgrey", "orange", "navy"), combine = TRUE) + ggtitle("ADRN and MES Scores")

saveplots(FeatureplotAdrnMes, "../BM Publication/", "Featureplot ADRN_MES_Score", w = 3500)
svg("Featureplot ADRN_MES_Score.svg", width = 12, height = 6)
FeatureplotAdrnMes
dev.off()

ScatterplotSplit <- FeatureScatter(IntegratedObject, feature1 = "ADRN_Score1", feature2 = "MES_Score1", split.by = "seurat_clusters", ncol = 7, group.by = "seurat_clusters", cols = Cluster_colours)

saveplots(ScatterplotSplit, "../BM Publication/", "Scatterplot ADRN_MES_Score split", w = 2000)
svg("Scatterplot ADRN_MES_Score split.svg", width = 15, height = 8)
ScatterplotSplit
dev.off()

ScatterplotAM <- FeatureScatter(IntegratedObject, feature1 = "ADRN_Score1", feature2 = "MES_Score1", group.by = "seurat_clusters", cols = Cluster_colours) + ggtitle("ADRN vs MES Score") + geom_smooth(method = 'lm')

saveplots(ScatterplotAM, "../BM Publication/", "Scatterplot ADRN_MES_Score")
svg("Scatterplot ADRN_MES_Score.svg")
ScatterplotAM
dev.off()

#Calculate average score per cluster, ADRN score and MES scores are stored as metadata for each cell
ADRNscores  <- aggregate(IntegratedObject$ADRN_Score1, by = list(Cluster = IntegratedObject$seurat_clusters), FUN = mean)
MESscores  <- aggregate(IntegratedObject$MES_Score1, by = list(Cluster = IntegratedObject$seurat_clusters), FUN = mean)
ADRNMESdiff <- aggregate(IntegratedObject$ADRNMESdiff, by = list(Cluster = IntegratedObject$seurat_clusters), FUN = mean)

#Barplot of average ADRN and MES score per cluster. 2 Bars per cluster, one ADRN and one MES, with different colors
scoreDF <- data.frame(Cluster = rep(ADRNscores$Cluster, 3), Score = c(ADRNscores$x, MESscores$x, ADRNMESdiff$x), Type = rep(c("ADRN", "MES", "Difference"), each = nrow(ADRNscores)))
BarplotAMD <- ggplot(scoreDF, aes(x = factor(Cluster), y = Score, fill = Type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("ADRN" = "orange", "MES" = "navy", "Difference" = "red")) +
  ggtitle("Average ADRN and MES Score and difference per Cluster") +
  xlab("Cluster") +
  ylab("Average Score") +
  theme_minimal()

saveplots(BarplotAMD, "../BM Publication/", "Barplot ADRN_MES_Score")
svg("Barplot ADRN_MES_Score.svg")
BarplotAMD
dev.off()


#Percentage of cells with higher ADRN than MES score, or higher MES score than ADRN score, per cluster.
scoreDF2 <- data.frame(Cluster = unique(IntegratedObject$seurat_clusters), ADRN_Higher = NA, MES_Higher = NA)
for (clust in scoreDF2$Cluster) {
  cells_in_cluster <- WhichCells(IntegratedObject, ident = clust)
  ADRN_higher <- sum(IntegratedObject$ADRN_Score1[cells_in_cluster] > IntegratedObject$MES_Score1[cells_in_cluster])
  MES_higher <- sum(IntegratedObject$MES_Score1[cells_in_cluster] > IntegratedObject$ADRN_Score1[cells_in_cluster])
  total_cells <- length(cells_in_cluster)
  scoreDF2$ADRN_Higher[scoreDF2$Cluster == clust] <- ADRN_higher / total_cells * 100
  scoreDF2$MES_Higher[scoreDF2$Cluster == clust] <- MES_higher / total_cells * 100
}
scoreDF2_long <- scoreDF2 %>% pivot_longer(cols = c("ADRN_Higher", "MES_Higher"), names_to = "Type", values_to = "Percentage")
ggplot(scoreDF2_long, aes(x = factor(Cluster), y = Percentage, fill = Type)) +
  geom_bar(stat = "identity", position = "stack") +
  scale_fill_manual(values = c("ADRN_Higher" = "orange", "MES_Higher" = "navy"), labels = c("ADRN Higher", "MES Higher")) +
  geom_hline(yintercept = 50, linetype = "dashed") +
  ggtitle("Percentage of Cells with Higher ADRN or MES Score per Cluster") +
  xlab("Cluster") +
  ylab("Percentage of Cells") +
  theme_minimal()

```

###Checking BM markers
```{r Removing stuff :)}
rm(cellLineLGND, CellLineTissueCompDF, clusterDF, clusterDF2, clusterDF3, clusterLGND, dataset_information, fullHTMap, h0, h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12, h13, Heatmap1, Heatmap2, Heatmap3, Heatmap4, Heatmap5, Heatmap6, Heatmap7, Heatmap8, Heatmap9, Heatmap10, Heatmap11, Heatmap12, Heatmap13, Heatmap1Matr, Heatmap2Matr, Heatmap3Matr, Heatmap4Matr, Heatmap5Matr, Heatmap6Matr, Heatmap7Matr, Heatmap8Matr, Heatmap9Matr, Heatmap10Matr, Heatmap11Matr, Heatmap12Matr, Heatmap13Matr, Heatmap1Annotation, Heatmap2Annotation, Heatmap3Annotation, Heatmap4Annotation, Heatmap5Annotation, Heatmap6Annotation, Heatmap7Annotation, Heatmap8Annotation, Heatmap9Annotation, Heatmap10Annotation, Heatmap11Annotation, Heatmap12Annotation, Heatmap13Annotation, included_dataset_information, LGNDs, matrixLGND, metadata_to_add, subplots, TissueCompDF, typeLGND, BM1comp, BM1plot, BM2comp, BM2plot, BM3comp, BM3plot, BMcomp, BMVec, cluster, Clusters, clusterVec, clusterVec2, clusterVec3, colour_use_count, comp, i, mouse_ID_sorted, new.cluster.ids, PDX_Site, PDX1Vec, PDX2Vec, PDX3Vec, PDXandSite, PDXvec, PDXvec2, PT1comp, PT1plot, PT2comp, PT2plot, PT3comp, PT3plot, PTcomp, PTVec, sample_indices, Site, TissueVec, title_colors, col_fun, pie_colours)
gc()
```


```{r Significant gene list up and down from Mast}
chosenGenes <- read_excel("~/Forskning/Neuroblastoma Met/BM Publication/Från Gustav/Chosen Metastasis Markers (Executive Summary).xlsx")
AllResults <- read_excel("~/Forskning/Neuroblastoma Met/BM Publication/Från Gustav/Merged Gene List with Fold-Changes & GSEA (MAST Random Slope, Absolute nFeature).xlsx")
chosenGenesNames <- chosenGenes$Gene

hist(MastResult$`Pr(>Chisq)`)

UpGenesMast <- MastResult$primerid[which(MastResult$coef > 0.25 & MastResult$`Pr(>Chisq)` < 0.05 & MastResult$qvalue < 0.05)]
DownGenesMast <- MastResult$primerid[which(MastResult$coef < 0.25 & MastResult$`Pr(>Chisq)` < 0.05 & MastResult$qvalue < 0.05)]
SignGenesMast <- c(UpGenesMast, DownGenesMast)
```

```{r Dotplot of upregulated genes}
IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-3_BM", "LU-NB-2_BM", "LU-NB-1_BM", "LU-NB-3_PT", "LU-NB-2_PT", "LU-NB-1_PT"))
DotPlot(IntegratedObject, features = UpGenesMast, group.by = "Cell_Line_n_Tissue") + RotatedAxis()
IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"))

```

```{r Heatmap of Up genes}
IntegratedObject <- ScaleData(IntegratedObject, assay = "SCT", features = UpGenesMast)
HeatmapSer <- subset(IntegratedObject, features = UpGenesMast)
HeatmapMatr <- GetAssayData(HeatmapSer, assay = "SCT", layer = "scale.data")
HeatmapMatr <- HeatmapMatr[order(factor(rownames(HeatmapMatr), levels = UpGenesMast)), ]

options(expressions = 500000) #Because it is very very nested, gives error

HeatmapAnnotation <- HeatmapAnnotation(PDX = HeatmapSer$Cell_Line_n, Location = HeatmapSer$Tissue, col = list(PDX = PDX_colours, Location = Tissue_colours), annotation_label = c("PDX", "Site"), show_legend = FALSE)
col_fun = colorRamp2(c(-2, 0, 2), c("#FF00FF", "#000000", "#FFFF00"))

h <- Heatmap(HeatmapMatr, name = "clusteredHeatmap", cluster_rows = TRUE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = TRUE, top_annotation = HeatmapAnnotation, col = col_fun, use_raster = FALSE, column_title = "Clustered heatmap", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
typeLGND <- Legend(labels = c("BM", "PT"), title = "Site", legend_gp = gpar(fill = Tissue_colours))
LGNDs <- packLegend(matrixLGND, cellLineLGND, typeLGND)

Figure9 <- draw(h, annotation_legend_list = LGNDs)
Figure9

#saveplots(Figure9, "../", "Heatmap DEG")
cairo_ps("Heatmap DEG.eps", width = 3000, height = 2500)
Figure9
dev.off()
png("Heatmap DEG.png", width = 3000, height = 2500, res = 300)
Figure9
dev.off()
svg("Heatmap DEG.svg", width = 15, height = 8)
Figure9
dev.off()
```

```{r Heatmap of top 50 up and down}
Top50Up <- UpGenesMast[1:50]
Top50Down <- DownGenesMast[1:50]
HeatmapGeneList <- c(Top50Up, Top50Down)

IntegratedObject <- ScaleData(IntegratedObject, assay = "SCT", features = HeatmapGeneList)
HeatmapSer <- subset(IntegratedObject, features = HeatmapGeneList)
HeatmapMatr <- GetAssayData(HeatmapSer, assay = "SCT", layer = "scale.data")
HeatmapMatr <- HeatmapMatr[order(factor(rownames(HeatmapMatr), levels = HeatmapGeneList)), ]

options(expressions = 500000) #Because it is very very nested, gives error

HeatmapAnnotation <- HeatmapAnnotation(PDX = HeatmapSer$Cell_Line_n, Location = HeatmapSer$Tissue, col = list(PDX = PDX_colours, Location = Tissue_colours), annotation_label = c("PDX", "Site"), show_legend = FALSE)
HeatmapAnnotationRow <- rowAnnotation(Signature = ifelse(rownames(HeatmapMatr) %in% Top50Up, "BM", "PT"), show_legend = FALSE, col = list(Signature = Tissue_colours), annotation_label = c(" "))

h2 <- Heatmap(HeatmapMatr, name = "clusteredHeatmap", cluster_rows = TRUE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = TRUE, top_annotation = HeatmapAnnotation, left_annotation = HeatmapAnnotationRow, col = col_fun, use_raster = FALSE, column_title = "Clustered Heatmap", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
typeLGND <- Legend(labels = c("BM", "PT"), title = "Site", legend_gp = gpar(fill = Tissue_colours))
GeneSignLGND <- Legend(labels = c("BM", "PT"), title = "Gene signature", legend_gp = gpar(fill = Tissue_colours))
LGNDs2 <- packLegend(matrixLGND, cellLineLGND, typeLGND, GeneSignLGND)

HeatmapTop50 <- draw(h2, annotation_legend_list = LGNDs2)

cairo_ps("Heatmap DEG top50.eps", width = 3000, height = 3500)
HeatmapTop50
dev.off()
png("Heatmap DEG top50.png", width = 3000, height = 3500, res = 300)
HeatmapTop50
dev.off()
svg("Heatmap DEG top50.svg", width = 15, height = 10)
HeatmapTop50
dev.off()
```



```{r Heatmap only BM}
OnlyBM <- subset(IntegratedObject, Tissue == "BM")

OnlyBM <- ScaleData(OnlyBM, assay = "SCT", features = UpGenesMast)
BMHeatmapSer <- subset(OnlyBM, features = UpGenesMast)
BMHeatmapMatr <- GetAssayData(BMHeatmapSer, assay = "SCT", layer = "scale.data")
BMHeatmapMatr <- BMHeatmapMatr[order(factor(rownames(BMHeatmapMatr), levels = UpGenesMast)), ]

HeatmapAnnotationBM <- HeatmapAnnotation(PDX = BMHeatmapSer$Cell_Line_n, col = list(PDX = PDX_colours), annotation_label = c("PDX"), show_legend = FALSE)

hBM <- Heatmap(BMHeatmapMatr, name = "clusteredHeatmap", cluster_rows = TRUE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = TRUE, top_annotation = HeatmapAnnotationBM, col = col_fun, use_raster = FALSE, column_title = "Clustered heatmap BM", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
LGNDsBM <- packLegend(matrixLGND, cellLineLGND)

HeatmapBM <- draw(hBM, annotation_legend_list = LGNDsBM)

cairo_ps("Heatmap DEG BM.eps", width = 2000, height = 2000)
HeatmapBM
dev.off()
png("Heatmap DEG BM.png", width = 2000, height = 2000, res = 300)
HeatmapBM
dev.off()
svg("Heatmap DEG BM.svg", width = 12, height = 8)
HeatmapBM
dev.off()
```


```{r Heatmap with BM-A and BM-B}

HeatmapAnnotationBM <- HeatmapAnnotation(PDX = BMHeatmapSer$Cell_Line_n, col = list(PDX = PDX_colours), annotation_label = c("PDX"), show_legend = FALSE)

HeatmapAnnotationRowBM <- rowAnnotation(Signature = ifelse(rownames(HeatmapMatr) %in% BMAgenes, "BM-A", "BM-B"), show_legend = FALSE, col = list(Signature = c("BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000")), annotation_label = c(" "))

hBM2 <- Heatmap(BMHeatmapMatr, name = "clusteredHeatmap", cluster_rows = TRUE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HeatmapAnnotationBM, left_annotation = HeatmapAnnotationRowBM, col = col_fun, use_raster = FALSE, column_title = "Clustered heatmap BM", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
SignatureLGND <- Legend(labels = c("BM-A Like", "BM-B Like"), title = "Gene signature", legend_gp = gpar(fill = c("BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000")))
LGNDsBM2 <- packLegend(matrixLGND, cellLineLGND, SignatureLGND)

HeatmapBM2 <- draw(hBM2, annotation_legend_list = LGNDsBM2)

cairo_ps("Heatmap DEG BM seperated on signature.eps", width = 2000, height = 2000)
HeatmapBM2
dev.off()
png("Heatmap DEG BM seperated on signature.png", width = 2000, height = 2000, res = 300)
HeatmapBM2
dev.off()
svg("Heatmap DEG BM seperated on signature.svg", width = 12, height = 8)
HeatmapBM2
dev.off()
```



```{r Heatmap seperated on site}
OnlyBM <- subset(HeatmapSer, Tissue == "BM")
OnlyPT <- subset(HeatmapSer, Tissue == "PT")

HeatmapMatrBM <- GetAssayData(OnlyBM, assay = "SCT", layer = "scale.data")
HeatmapMatrBM <- HeatmapMatrBM[order(factor(rownames(HeatmapMatrBM), levels = HeatmapGeneList)), ]

HeatmapMatrPT <- GetAssayData(OnlyPT, assay = "SCT", layer = "scale.data")
HeatmapMatrPT <- HeatmapMatrPT[order(factor(rownames(HeatmapMatrPT), levels = HeatmapGeneList)), ]

HeatmapAnnotationBM <- HeatmapAnnotation(PDX = OnlyBM$Cell_Line_n, Location = OnlyBM$Tissue, col = list(PDX = PDX_colours, Location = Tissue_colours), annotation_label = c("PDX", "Site"), show_legend = FALSE)
HeatmapAnnotationPT <- HeatmapAnnotation(PDX = OnlyPT$Cell_Line_n, Location = OnlyPT$Tissue, col = list(PDX = PDX_colours, Location = Tissue_colours), annotation_label = c("PDX", "Site"), show_legend = FALSE)
HeatmapAnnotationRow <- rowAnnotation(Signature = ifelse(rownames(HeatmapMatr) %in% Top50Up, "BM", "PT"), show_legend = FALSE, col = list(Signature = Tissue_colours), annotation_label = c(" "))

BMh <- Heatmap(HeatmapMatrBM, name = "clusteredHeatmap", cluster_rows = FALSE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HeatmapAnnotationBM, col = col_fun, use_raster = FALSE, column_title = "Clustered Heatmap", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

PTh<- Heatmap(HeatmapMatrPT, name = "clusteredHeatmap", cluster_rows = FALSE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HeatmapAnnotationPT, right_annotation = HeatmapAnnotationRow, col = col_fun, use_raster = FALSE, column_title = "Clustered Heatmap", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

hAll <- BMh + PTh
HeatmapTop50unClust <- draw(hAll, ht_gap = unit(1, "mm"), annotation_legend_list = LGNDs2)

png("Heatmap DEG not clustered.png", width = 3000, height = 3500, res = 300)
HeatmapTop50unClust
dev.off()
svg("Heatmap DEG not clustered.svg", width = 15, height = 10)
HeatmapTop50unClust
dev.off()
```


```{r gseaKEGG och gseaGO från MAST}
#Skapa lista med fold-change
gseaGeneList <- MastResult$coef
names(gseaGeneList) <- MastResult$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Plotting KEGG
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
#I want the dataframe to have all the pathways with negative NES first, ordered by p.adjust, then all pathways with positive NES, ordered by p.adjust.
#DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$NES < 0, DFKEGGResult$p.adjust), ]
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

Figure10 <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )
Figure10

DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
#DFGOResult <- DFGOResult[order(DFGOResult$NES < 0, DFGOResult$p.adjust), ]
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

Figure11 <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )
Figure11

saveplots(Figure10, "../BM Publication/", "Barplot GSEA KEGG (Neg p.adjust)", w = 2000)
svg("Barplot GSEA KEGG (Neg p.adjust).svg", width = 20)
Figure10
dev.off()
saveplots(Figure11, "../BM Publication/", "Barplot GSEA GO (Neg p.adjust)", w = 2000)
svg("Barplot GSEA GO (Neg p.adjust).svg", width = 20)
Figure11
dev.off()


#DFKEGG10 <- rbind(head(KeggPos[order(KeggPos$p.adjust), ], 10), head(KeggNeg[order(KeggNeg$p.adjust), ], 13))
#DFGO10 <- rbind(head(GOPos[order(GOPos$p.adjust), ], 10), head(GONeg[order(GONeg$p.adjust), ], 10))
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), DFKEGGResult[DFKEGGResult$Description %in% UpKegg, ])
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

Figure16 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
Figure17 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(Figure16, "../BM Publication/", "Barplot GSEA KEGG top10")
svg("Barplot GSEA KEGG top10.svg")
Figure16
dev.off()
saveplots(Figure17, "../BM Publication/", "Barplot GSEA GO top10", w = 1100)
svg("Barplot GSEA GO top10.svg")
Figure17
dev.off()
```

```{r Calculating BM scores}
IntegratedObject <- AddModuleScore(IntegratedObject, features = list(chosenGenesNames), name = "BM1score")
IntegratedObject <- AddModuleScore(IntegratedObject, features = list(UpGenesMast), name = "BM2score")

BMBgenes <- c("RPL27A", "RPS20", "RPL9", "RPL27", "RPS17", "HIST1H4C", "PPIA", "TMSB10", "MIF", "ATP5F1E", "ATP5ME", "PCBP2", "C4orf48")
BMAgenes <- UpGenesMast[!UpGenesMast %in% BMBgenes]

DotplotGenes <- c(c(head(BMBgenes, n = 5)), c(head(BMAgenes, n = 5)), c(head(DownGenesMast, n = 5)))

IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-3_BM", "LU-NB-2_BM", "LU-NB-1_BM", "LU-NB-3_PT", "LU-NB-2_PT", "LU-NB-1_PT"))
Figure8 <- DotPlot(IntegratedObject, features = DotplotGenes, group.by = "Cell_Line_n_Tissue") + RotatedAxis()
IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"))
Figure8

IntegratedObject <- AddModuleScore(IntegratedObject, features = list(BMBgenes), name = "BM-Bscore")
IntegratedObject <- AddModuleScore(IntegratedObject, features = list(BMAgenes), name = "BM-Ascore")
IntegratedObject$BMdiff <- scale(IntegratedObject$BM-Ascore1) - scale(IntegratedObject$BM-Bscore1)

saveRDS(BMAgenes, "BMAgenes.rds")
saveRDS(BMBgenes, "BMBgenes.rds")

IntegratedObject$Cell_Line_n_Tissue <- factor(IntegratedObject$Cell_Line_n_Tissue, levels = c("LU-NB-1_PT", "LU-NB-1_BM", "LU-NB-2_PT", "LU-NB-2_BM", "LU-NB-3_PT", "LU-NB-3_BM"))

VlnBMATissue <- VlnPlot(IntegratedObject, features = c("BM-Ascore1"), group.by = "Tissue", pt.size = 0, cols = Tissue_colours)+ geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + 
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")
VlnBMBTissue <- VlnPlot(IntegratedObject, features = c("BM-Bscore1"), group.by = "Tissue", pt.size = 0, cols = Tissue_colours)+ geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + 
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")
VlnBMdiffTissue <- VlnPlot(IntegratedObject, features = c("BMdiff"), group.by = "Tissue", pt.size = 0, cols = Tissue_colours)+ geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + 
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")

BMScoreSite <- wrap_plots(VlnBMATissue, VlnBMBTissue, VlnBMdiffTissue, ncol = 3)

VlnBMAPDX <- VlnPlot(IntegratedObject, features = c("BM-Ascore1"), group.by = "Cell_Line_n_Tissue", pt.size = 0, cols = c("LU-NB-1_PT" = "#295692", "LU-NB-1_BM" = "#295692", "LU-NB-2_PT" = "#d09e53", "LU-NB-2_BM" = "#d09e53", "LU-NB-3_PT" = "#529fa6", "LU-NB-3_BM" = "#529fa6")) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")
VlnBMBPDX <- VlnPlot(IntegratedObject, features = c("BM-Bscore1"), group.by = "Cell_Line_n_Tissue", pt.size = 0, cols = c("LU-NB-1_PT" = "#295692", "LU-NB-1_BM" = "#295692", "LU-NB-2_PT" = "#d09e53", "LU-NB-2_BM" = "#d09e53", "LU-NB-3_PT" = "#529fa6", "LU-NB-3_BM" = "#529fa6")) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")
VlnBMDPDX <- VlnPlot(IntegratedObject, features = c("BMdiff"), group.by = "Cell_Line_n_Tissue", pt.size = 0, cols = c("LU-NB-1_PT" = "#295692", "LU-NB-1_BM" = "#295692", "LU-NB-2_PT" = "#d09e53", "LU-NB-2_BM" = "#d09e53", "LU-NB-3_PT" = "#529fa6", "LU-NB-3_BM" = "#529fa6")) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black")


BMScorePDXSite <- wrap_plots(VlnBMAPDX, VlnBMBPDX, VlnBMDPDX, ncol = 3)

saveplots(BMScoreSite, "../BM Publication/", "VlnPlot BMscore Site", w = 2000)
saveplots(BMScorePDXSite, "../BM Publication/", "VlnPlot BMscore PDX Site", w = 3000)
svg("VlnPlot BMscore Site.svg", width = 10)
BMScoreSite
dev.off()
svg("VlnPlot BMscore PDX Site.svg", width = 12)
BMScorePDXSite
dev.off()

ScatterplotBMscoresAll <- FeatureScatter(IntegratedObject, feature1 = "BM-Ascore1", feature2 = "BM-Bscore1", group.by = "Tissue", cols = Tissue_colours) + geom_smooth(method = 'lm') + theme(plot.title = element_text(face = "bold"), axis.title = element_text(size = 12, color = "black"), axis.text = element_text(size = 10, color = "black"))
ScatterplotBMscores1 <- FeatureScatter(subset(IntegratedObject, Cell_Line_n == "LU-NB-1"), feature1 = "BM-Ascore1", feature2 = "BM-Bscore1", group.by = "Tissue", cols = Tissue_colours, split.by = "Cell_Line_n") + geom_smooth(method = 'lm') + theme(plot.title = element_text(face = "bold", colour = PDX_colours[1]), axis.title = element_text(size = 12, color = "black"), axis.text = element_text(size = 10, color = "black"))
ScatterplotBMscores2 <- FeatureScatter(subset(IntegratedObject, Cell_Line_n == "LU-NB-2"), feature1 = "BM-Ascore1", feature2 = "BM-Bscore1", group.by = "Tissue", cols = Tissue_colours, split.by = "Cell_Line_n") + geom_smooth(method = 'lm') + theme(plot.title = element_text(face = "bold", colour = PDX_colours[2]), axis.title = element_text(size = 12, color = "black"), axis.text = element_text(size = 10, color = "black"))
ScatterplotBMscores3 <- FeatureScatter(subset(IntegratedObject, Cell_Line_n == "LU-NB-3"), feature1 = "BM-Ascore1", feature2 = "BM-Bscore1", group.by = "Tissue", cols = Tissue_colours, split.by = "Cell_Line_n") + geom_smooth(method = 'lm') + theme(plot.title = element_text(face = "bold", colour = PDX_colours[3]), axis.title = element_text(size = 12, color = "black"), axis.text = element_text(size = 10, color = "black"))

ScatterBMscore <- wrap_plots(ScatterplotBMscoresAll, ScatterplotBMscores1, ScatterplotBMscores2, ScatterplotBMscores3, ncol = 2)

saveplots(ScatterBMscore, "../BM Publication/", "Scatterplot BM-A to BM-B score")
svg("Scatterplot BM-A to BM-B score.svg")
ScatterBMscore
dev.off()

BMAcells <- subset(IntegratedObject, Tissue == "BM" & `BM-Ascore1` > 0)
BMBcells <- subset(IntegratedObject, Tissue == "BM" & `BM-Bscore1` > 0)
VlnPlot(BMAcells, features = c("BM-Ascore1"), group.by = "Tissue")
VlnPlot(BMBcells, features = c("BM-Ascore1"), group.by = "Tissue")
VlnPlot(BMAcells, features = c("BM-Bscore1"), group.by = "Tissue")
VlnPlot(BMBcells, features = c("BM-Bscore1"), group.by = "Tissue")
VlnPlot(BMAcells, features = c("BMdiff"), group.by = "Tissue")
VlnPlot(BMBcells, features = c("BMdiff"), group.by = "Tissue")
BMAmean <- mean(BMAcells$BMAscore1)
BMBmean <- mean(BMBcells$BMBscore1)


```

```{r Finding PT cells with high BMscore}
PTCells <- subset(IntegratedObject, Tissue == "PT")

FeaturePlot(PTCells, features = "BM-Ascore1")
FeaturePlot(PTCells, features = "BM-Bscore1")
FeaturePlot(PTCells, features = c("BM-Ascore1", "BM-Bscore1"), blend = TRUE, combine = FALSE)

PTCells$seurat_clusters <- factor(PTCells$seurat_clusters, levels = 1:11)

VlnBMA <- VlnPlot(PTCells, features = c("BM-Ascore1"), group.by = "seurat_clusters", cols = Cluster_colours, pt.size = 0, sort = "increasing") + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + 
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + 
    ggpubr::stat_compare_means(method = "anova", label.y = max(PTCells@meta.data$`BM-Ascore1`, na.rm = TRUE) * 0.95)
VlnBMB <- VlnPlot(PTCells, features = c("BM-Bscore1"), group.by = "seurat_clusters", cols = Cluster_colours, pt.size = 0, sort = "increasing") + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) +
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + 
    ggpubr::stat_compare_means(method = "anova", label.y = max(PTCells@meta.data$`BM-Bscore1`, na.rm = TRUE) * 0.95)
VlnBMdiff <- VlnPlot(PTCells, features = c("BMdiff"), group.by = "seurat_clusters", cols = Cluster_colours, pt.size = 0, sort = "increasing") + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + 
    stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + 
    ggpubr::stat_compare_means(method = "anova", label.y = max(PTCells@meta.data$BMdiff, na.rm = TRUE) * 0.95)

BMScoreCluster <- wrap_plots(VlnBMA, VlnBMB, VlnBMdiff, ncol = 3)
BMScoreCluster

saveplots(BMScoreCluster, "../BM Publication/", "VlnPlot BMscore PTCluster", w = 2000)
svg("VlnPlot BMscore PTCluster.svg", width = 12)
BMScoreCluster
dev.off()

PTCells$BMALike <- ifelse(PTCells$seurat_clusters %in% c("10"), "BM-A Like", "Not BM-A Like")
PTCells$BMBLike <- ifelse(PTCells$seurat_clusters %in% c("7"), "BM-B Like", "Not BM-B Like")
PTCells$BMLike <- ifelse(PTCells$seurat_clusters %in% c("10", "BM-A Like", ifelse(PTCells$seuratclusters %in% c("7"), "BM-B Like", "Other")))

Figure12 <- DimPlot(PTCells, reduction = "umap.harmony", group.by = "BMALike", order = c("BM-A Like", "Not BM-A Like"), cols = c("BM-A Like" = "#FF7F7F", "Not BM-A Like" = "lightgrey")) + ggtitle("BM-A Like PT cells") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
Figure13 <- DimPlot(PTCells, reduction = "umap.harmony", group.by = "BMBLike", order = c("BM-B Like", "Not BM-B Like"), cols = c("BM-B Like" = "#990000", "Not BM-B Like" = "lightgrey")) + ggtitle("BM-B Like PT cells") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")

#UMAPs seperated on PDX
BMA1 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-1"), reduction = "umap.harmony", group.by = "BMALike", order = c("BM-A Like", "Not BM-A Like"), cols = c("BM-A Like" = "#FF7F7F", "Not BM-A Like" = "lightgrey"))+ ggtitle("BM-A Like LU-NB-1") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[1])) + ylab("UMAP 2")
BMA2 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-2"), reduction = "umap.harmony", group.by = "BMALike", order = c("BM-A Like", "Not BM-A Like"), cols = c("BM-A Like" = "#FF7F7F", "Not BM-A Like" = "lightgrey"))+ ggtitle("BM-A Like LU-NB-2") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[2])) + ylab("UMAP 2")
BMA3 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-3"), reduction = "umap.harmony", group.by = "BMALike", order = c("BM-A Like", "Not BM-A Like"), cols = c("BM-A Like" = "#FF7F7F", "Not BM-A Like" = "lightgrey"))+ ggtitle("BM-A Like LU-NB-3") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[3])) + ylab("UMAP 2")
BMB1 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-1"), reduction = "umap.harmony", group.by = "BMBLike", order = c("BM-B Like", "Not BM-B Like"), cols = c("BM-B Like" = "#990000", "Not BM-B Like" = "lightgrey"))+ ggtitle("BM-B Like LU-NB-1") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[1])) + ylab("UMAP 2")
BMB2 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-2"), reduction = "umap.harmony", group.by = "BMBLike", order = c("BM-B Like", "Not BM-B Like"), cols = c("BM-B Like" = "#990000", "Not BM-B Like" = "lightgrey"))+ ggtitle("BM-B Like LU-NB-2") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[2])) + ylab("UMAP 2")
BMB3 <- DimPlot(PTCells, cells = WhichCells(PTCells, expression = Cell_Line_n == "LU-NB-3"), reduction = "umap.harmony", group.by = "BMBLike", order = c("BM-B Like", "Not BM-B Like"), cols = c("BM-B Like" = "#990000", "Not BM-B Like" = "lightgrey"))+ ggtitle("BM-B Like LU-NB-3") + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.x = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), legend.position = "none", plot.title = element_text(colour = PDX_colours[3])) + ylab("UMAP 2")
UMAPBMLikeSplit <- wrap_plots(Figure12, BMA1, BMA2, BMA3, Figure13, BMB1, BMB2, BMB3, ncol = 4)

saveplots(UMAPBMLikeSplit, "../BM Publication/", "UMAP BM Like split", w = 1400)
svg("UMAP BM Like split.svg", width = 10)
UMAPBMLikeSplit
dev.off()
UMAPBMLikeSplit

#Barplot with % BMALike per Cell line
CellLine <- c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "Extra")
Signature <- c(rep(c("BM"), 3), "Extra")
Percentage <- c(c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-3")))), c(0.05))

barplotData1 <- data.frame(CellLine, Signature, Percentage)

Figure14 <- ggplot(barplotData1, aes(fill=Signature, y=Percentage, x=CellLine)) + 
  geom_col() + 
  ggtitle("Percentage cells with BM-A profile") +
  scale_fill_manual(values = c("BM" = "#E6550D", "Extra" = "white")) +
  scale_y_continuous(breaks = seq(0, 0.10, by = 0.01), labels = scales::label_percent(), expand = c(0, 0)) +
  scale_x_discrete(limits = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "Extra"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3", "")) +
  theme_minimal() +
  geom_text(aes(label = 100*round(Percentage, 4)), position = position_dodge(width = 1), vjust = -0.5, color = "black", size = 4) +
  theme(
  legend.position = "right",
  legend.title = element_blank(),
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.y = element_blank(),
  axis.line.y = element_line(color = "black", linewidth = 1.5, lineend = "square"),
  axis.ticks.y = element_line(color = "black", linewidth = 1.5),
  axis.ticks.length.y = unit(0.2, "cm"),
  axis.line.x = element_blank(),
  axis.text.x = element_text(size = 15, , colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 15),
  panel.grid = element_blank(),
  text = element_text(size = 12, color = "black")
)
Figure14

#Barplot with % BMBLike per Cell line
CellLine <- c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "Extra")
Signature <- c(rep(c("BM"), 3), "Extra")
Percentage <- c(c(length(WhichCells(PTCells, expression = BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(PTCells, expression = BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(PTCells, expression = BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-3")))), c(0.3))

barplotData2 <- data.frame(CellLine, Signature, Percentage)

Figure15 <- ggplot(barplotData2, aes(fill=Signature, y=Percentage, x=CellLine)) + 
  geom_col() + 
  ggtitle("Percentage cells with BM-B profile") +
  scale_fill_manual(values = c("BM" = "#E6550D", "Extra" = "white")) +
  scale_y_continuous(breaks = seq(0, 0.40, by = 0.05), labels = scales::label_percent(), expand = c(0, 0)) +
  scale_x_discrete(limits = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT", "Extra"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3", "")) +
  theme_minimal() +
  geom_text(aes(label = 100*round(Percentage, 4)), position = position_dodge(width = 1), vjust = -0.5, color = "black", size = 4) +
  theme(
  legend.position = "right",
  legend.title = element_blank(),
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.y = element_blank(),
  axis.line.y = element_line(color = "black", linewidth = 1.5, lineend = "square"),
  axis.ticks.y = element_line(color = "black", linewidth = 1.5),
  axis.ticks.length.y = unit(0.2, "cm"),
  axis.line.x = element_blank(),
  axis.text.x = element_text(size = 15, , colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 15),
  panel.grid = element_blank(),
  text = element_text(size = 12, color = "black")
)

CellLine <- c(rep(c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT"), each = 3))
Signature <- c(rep(c("BM-A Like", "Both", "BM-B Like"), times = 3))
Percentage <- c(c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "Not BM-B Like" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(PTCells, expression = BMALike == "Not BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "Not BM-B Like" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(PTCells, expression = BMALike == "Not BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "Not BM-B Like" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-3")))), c(length(WhichCells(PTCells, expression = BMALike == "BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-3")))), c(length(WhichCells(PTCells, expression = BMALike == "Not BM-A Like" & BMBLike == "BM-B Like" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(PTCells, Cell_Line_n == "LU-NB-3")))))

barplotData3 <- data.frame(CellLine, Signature, Percentage)
ggplot(barplotData3, aes(fill=factor(Signature, levels = c("BM-B Like", "Both", "BM-A Like")), y=Percentage, x=CellLine)) + 
  geom_bar(position = "stack", stat = "identity", width = 0.8) + 
  geom_col() + 
  ggtitle("Percentage cells with BM profile") +
  scale_fill_manual(values = c("Both" = "#FF0000", "BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000")) +
  scale_y_continuous(breaks = seq(0, 0.30, by = 0.05), labels = scales::label_percent(), expand = c(0, 0)) +
  scale_x_discrete(limits = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3")) +
  theme_minimal() +
  geom_text(aes(label = ifelse(Percentage > 0.0001, 100*round(Percentage, 4), "")), position = position_stack(vjust = 1), vjust = -0.5, color = "black", size = 4) +
  theme(
  legend.position = "right",
  legend.title = element_blank(),
  axis.title.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.title.y = element_blank(),
  axis.line.y = element_line(color = "black", linewidth = 1.5, lineend = "square"),
  axis.ticks.y = element_line(color = "black", linewidth = 1.5),
  axis.ticks.length.y = unit(0.2, "cm"),
  axis.line.x = element_blank(),
  axis.text.x = element_text(size = 15, , colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 15),
  panel.grid = element_blank(),
  text = element_text(size = 12, color = "black")
)

Figure18 <- ggplot(barplotData3, aes(fill=Signature, y=Percentage, x=CellLine, size=8)) + 
  geom_bar(position = "dodge", stat = "identity", width = 0.9) + 
  ggtitle("Percentage of BM-A/BM-B Like PT Cells") +
  scale_fill_manual(values = c("Both" = "#FF0000", "BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000")) +
  scale_x_discrete(limits = c("LU-NB-1_PT", "LU-NB-2_PT", "LU-NB-3_PT"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3")) +
  scale_y_continuous(breaks = seq(0, 0.10, by = 0.01), labels = scales::label_percent(), expand = expansion(0, c(0, 0.05))) +
  geom_text(aes(label = 100*round(Percentage, 4)), 
            position = position_dodge(width = 0.8), vjust = -0.8, color =  "black", size = 3) +
  theme_minimal() +
  theme(
  axis.text.x = element_text(angle = 0, hjust = 0.5, size = 15, colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 10),
  text = element_text(size = 12, color = "black")
)

saveplots(Figure18, "../BM Publication/", "Barplot all BMLike PT Cells in PDX")
svg("Barplot all BMLike PT Cells in PDX.svg")
Figure18
dev.off()

Figure12
Figure13
Figure14
Figure15
Figure18
```

```{r Connection between BMA/BMB och ADRN/MES}
onlyBM <- subset(IntegratedObject, Tissue == "BM")
onlyBM$type <- ifelse(onlyBM$`BM-Ascore1` > BMAmean & onlyBM$`BM-Bscore1` > BMBmean, "Both", ifelse(onlyBM$`BM-Ascore1` > BMAmean, "BM-A", ifelse(onlyBM$`BM-Bscore1` > BMBmean, "BM-B", "Other")))

VlnPlot(onlyBM, features = c("BM-Ascore1", "BM-Bscore1", "BMdiff"), group.by = "type", pt.size = 0, cols = c("BM-A" = "#FF7F7F", "BM-B" = "#990000"))
VlnPlot(onlyBM, features = c("ADRN_Score1", "MES_Score1"), group.by = "type", pt.size = 0, cols = c("BM-A" = "#FF7F7F", "BM-B" = "#990000"))

AdrnMesBMtype <- VlnPlot(onlyBM, features = c("ADRNMESdiff"), group.by = "type", pt.size = 0, cols = c("BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000"))+ geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + ggpubr::stat_compare_means(method = "anova", label.y = max(onlyBM@meta.data$ADRNMESdiff, na.rm = TRUE) * 0.95)


ScatterStateBMtype1 <- FeatureScatter(onlyBM, cells = WhichCells(onlyBM, expression = Cell_Line_n == "LU-NB-1"), feature1 = "ADRNMESdiff", feature2 = "BMdiff", group.by = "Cell_Line_n", cols = c(PDX_colours)) + ggtitle("LU-NB-1: -0.24") + geom_smooth(method = 'lm') + NoLegend() + theme(axis.line = element_line(color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), plot.title = element_text(colour = PDX_colours[1])) + ylab("BM-A - BM-B") + xlab("Mes - Adrn") 
ScatterStateBMtype2 <- FeatureScatter(onlyBM, cells = WhichCells(onlyBM, expression = Cell_Line_n == "LU-NB-2"), feature1 = "ADRNMESdiff", feature2 = "BMdiff", group.by = "Cell_Line_n", cols = c(PDX_colours)) + ggtitle("LU-NB-2: 0.07") + geom_smooth(method = 'lm') + NoLegend() +  theme(axis.line = element_line(color = "black"), axis.title.y = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), plot.title = element_text(colour = PDX_colours[2])) + xlab("Mes - Adrn")
ScatterStateBMtype3 <- FeatureScatter(onlyBM, cells = WhichCells(onlyBM, expression = Cell_Line_n == "LU-NB-3"), feature1 = "ADRNMESdiff", feature2 = "BMdiff", group.by = "Cell_Line_n", cols = c(PDX_colours)) + ggtitle("LU-NB-3: -0.14") + geom_smooth(method = 'lm') + NoLegend() + theme(axis.line = element_line(color = "black"), axis.title.y = element_blank(), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1), plot.title = element_text(colour = PDX_colours[3])) + xlab("Mes - Adrn")
ScatterStateBMtype <- wrap_plots(ScatterStateBMtype1, ScatterStateBMtype2, ScatterStateBMtype3, ncol = 3)


saveplots(ScatterStateBMtype, "../BM Publication/", "Scatterplot BMdiff vs AdrnMesDiff", w = 2000)
svg("Scatterplot BMdiff vs AdrnMesDiff.svg", width = 12, height = 6)
ScatterStateBMtype
dev.off()
saveplots(AdrnMesBMtype, "../BM Publication/", "VlnPlot AdrnMesDiff in BMtype", w = 1000)
svg("VlnPlot AdrnMesDiff in BMtype.svg")
AdrnMesBMtype
dev.off()
```

```{r BMA and BMB comparison}
#Barplot of BMA/B cells in BM per PDX
CellLine <- c(rep(c("LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"), each = 3))
Signature <- c(rep(c("BM-A Cells", "Both", "BM-B Cells"), times = 3))
Percentage <- c(c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(onlyBM, expression = type == "Both" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(onlyBM, expression = type == "Both" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-3")))), c(length(WhichCells(onlyBM, expression = type == "Both" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-3")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-3")))))

barplotData4 <- data.frame(CellLine, Signature, Percentage)
BarplotBM <- ggplot(barplotData4, aes(fill=Signature, y=Percentage, x=CellLine, size=8)) + 
  geom_bar(position = "dodge", stat = "identity", width = 0.9) + 
  ggtitle("Percentage of BM-A/BM-B Cells") +
  scale_fill_manual(values = c("Both" = "#FF0000", "BM-A Cells" = "#FF7F7F", "BM-B Cells" = "#990000")) +
  scale_x_discrete(limits = c("LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3")) +
  scale_y_continuous(breaks = seq(0, 0.50, by = 0.1), labels = scales::label_percent(), expand = expansion(0, c(0, 0.05))) +
  geom_text(aes(label = 100*round(Percentage, 4)), 
            position = position_dodge(width = 0.8), vjust = -0.8, color =  "black", size = 3) +
  theme_minimal() +
  theme(
  axis.text.x = element_text(angle = 0, hjust = 0.5, size = 15, colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 10),
  text = element_text(size = 12, color = "black")
)

#Saving plot
saveplots(BarplotBM, "../BM Publication/", "Barplot BM type in BM")
svg("Barplot BM type in BM.svg")
BarplotBM
dev.off()
BarplotBM

```

```{r New umap with only BM cells}
#Reprocessing
DefaultAssay(onlyBM) <- "RNA"
onlyBM[["SCT"]] <- NULL 
onlyBM <- JoinLayers(onlyBM)
onlyBM[["RNA"]] <- split(onlyBM[["RNA"]], f = onlyBM$orig.ident)
onlyBM <- SCTransform(onlyBM, vars.to.regress = c("nFeature_RNA", 'nCount_RNA', "percent_mito", "cc_difference", "percent_ribo"), return.only.var.genes = FALSE, verbose = TRUE)
DefaultAssay(onlyBM) <- "SCT"
onlyBM <- RunPCA(onlyBM, seed.use = 1999,verbose = FALSE)
ElbowPlot(onlyBM, ndims = 50)
onlyBM <- IntegrateLayers(object = onlyBM, method = HarmonyIntegration, orig.reduction = "pca", dims = 1:30, new.reduction = "integrated.harmony", normalization.method = "SCT", k.weight = 50, verbose = FALSE)
onlyBM <- RunUMAP(onlyBM, reduction = "integrated.harmony", reduction.name = "umap.harmony", dims = 1:30, verbose = FALSE,seed.use = 1999)

#Plotting
UMAPBM <- DimPlot(onlyBM, reduction = "umap.harmony", group.by = "Cell_Line_n", cols = c(PDX_colours), pt.size = 0.8) + ggtitle("UMAP of BM cells") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
DimPlot(onlyBM, reduction = "umap.harmony", group.by = "type", cols = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Both" = "#FF0000", "Other" = "lightgrey"), pt.size = 0.8) + ggtitle("UMAP of BM cells") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
DimPlot(onlyBM, reduction = "umap.harmony", group.by = "type", cols = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Both" = "#FF0000", "Other" = "lightgrey"), pt.size = 0.8) + ggtitle("UMAP of BM cells") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")

saveplots(UMAPBM, "../BM Publication/", "UMAP BM by PDX", w = 1050)
svg("UMAP BM by PDX.svg")
UMAPBM
dev.off()
BarplotBM

#Combining features
FeaturePlot(onlyBM, features = c("BM-Ascore1", "BM-Bscore1"), reduction = "umap.harmony", order = TRUE, combine = FALSE, blend = TRUE)
FeaturePlot(onlyBM, features = c("ADRN_Score1", "MES_Score1"), reduction = "umap.harmony", blend = TRUE, combine = FALSE)

FeaturePlot(onlyBM, features = c("BM-Ascore1"), reduction = "umap.harmony", cols = c("lightgrey", "red")) + ggtitle("BM-A score") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
FeaturePlot(onlyBM, features = c("BM-Bscore1"), reduction = "umap.harmony", cols = c("lightgrey", "red")) + ggtitle("BM-B score") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
FeaturePlot(onlyBM, features = c("BMdiff"), reduction = "umap.harmony", cols = c("yellow", "#800080")) + ggtitle("BM-A - BM-B") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
```


```{r Saving all Plots}
setwd("~/Forskning/Neuroblastoma Met/BM Publication/")

#Function that saves plots, from Gustav
saveplots <- function(object,location,filename,w = 900,h = 900,pointsize = 12,res = 150){
  setwd("~/Forskning/Neuroblastoma Met/BM Publication/")
  png(paste0(location,filename,".png"),width = w, height = h, units = "px", pointsize = pointsize, res = res)
  print(object)
  dev.off()
  ggsave(path = location,filename = paste0(filename,".eps"), plot = object,width = w,height = h,dpi = res, units = "px")
}


saveplots(Figure1, "../BM Publication/", "UMAP PDX", w = 1050)
svg("UMAP PDX.svg", width = 9)
Figure1
dev.off()
saveplots(Figure2, "../BM Publication/", "UMAP split", w = 1200)
svg("UMAP split.svg", width = 9)
Figure2
dev.off()
saveplots(Figure3, "../BM Publication/", "UMAP Clustered", w = 1050)
svg("UMAP Clustered.svg", width = 9)
Figure3
dev.off()
saveplots(Figure4, "../BM Publication/", "Barplot Clusters in PDX")
svg("Barplot Clusters in PDX.svg")
Figure4
dev.off()

#saveplots(Figure5, "../", "Heatmap Clustermarkers")
cairo_ps("Heatmap Clustermarkers.eps", width = 4000, height = 2500)
Figure5
dev.off()
png("Heatmap Clustermarkers.png", width = 4000, height = 2500, res = 300)
Figure5
dev.off()
svg("Heatmap Clustermarkers.svg", width = 25, height = 15)
Figure5
dev.off()

saveplots(Figure6, "../BM Publication/", "Dotplot Clustermarkers", w = 3000)
svg("Dotplot Clustermarkers.svg", width = 20)
Figure6
dev.off()
saveplots(Figure7, "../BM Publication/", "Barplot Clusters in Site")
svg("Barplot Clusters in Site.svg")
Figure7
dev.off()
saveplots(Figure8, "../BM Publication/", "Dotplot DEG", w = 1000)
svg("Dotplot DEG.svg")
Figure8
dev.off()

saveplots(Figure12, "../BM Publication/", "UMAP BM1Like PT Cells", w = 1050)
svg("UMAP BM1Like PT Cells.svg", width = 9)
Figure12
dev.off()
saveplots(Figure13, "../BM Publication/", "UMAP BM2Like PT Cells", w = 1050)
svg("UMAP BM2Like PT Cells.svg", width = 9)
Figure13
dev.off()

saveplots(Figure14, "../BM Publication/", "Barplot BMALike PT Cells in PDX")
svg("Barplot BMALike PT Cells in PDX.svg")
Figure14
dev.off()
saveplots(Figure15, "../BM Publication/", "Barplot BMBLike PT Cells in PDX")
svg("Barplot BMBLike PT Cells in PDX.svg")
Figure15
dev.off()

saveplots(Figure18, "../BM Publication/", "Barplot all BMLike PT Cells in PDX")
svg("Barplot all BMLike PT Cells in PDX.svg")
Figure18
dev.off()
```

```{r Clustering BM cells}
resList <- list()
for (res in seq(0.01, 1.0, by = 0.01)) {
  #Find neighbors and clusters
  onlyBM <- FindNeighbors(onlyBM, reduction = "integrated.harmony", dims = 1:30)
  onlyBM <- FindClusters(onlyBM, resolution = res)
  
  #Count number of clusters
  clustnbr <- length(unique(onlyBM$seurat_clusters))
  
  #Add number of clusters to list
  resList[[as.character(res)]] <- clustnbr
}

#Ggplot of changes in cluster number with different resolutions
resDF <- data.frame(Resolution = as.numeric(names(resList)), ClusterNumber = unlist(resList))
ggplot(resDF, aes(x = Resolution, y = ClusterNumber)) +
  geom_line() +
  geom_point() +
  ggtitle("Number of Clusters at Different Resolutions") +
  xlab("Resolution") +
  ylab("Number of Clusters") +
  theme_minimal()

#13 cluster at res 0.15 seem to be a good choice
onlyBM <- FindNeighbors(onlyBM, reduction = "integrated.harmony", dims = 1:30)
onlyBM <- FindClusters(onlyBM, resolution = 0.30)

#Planar ut vid 2, 5, 9, 14 kluster. 9 Känns rimlig, res = 30.

#Setting cluster names 1-13
new.cluster.ids <- c(1:13) 
names(new.cluster.ids) <- levels(onlyBM)
onlyBM <- RenameIdents(onlyBM, new.cluster.ids)
onlyBM$seurat_clusters <- Idents(onlyBM)

UMAPBMClust <- DimPlot(onlyBM, reduction = "umap.harmony", group.by = "seurat_clusters", cols = Cluster_colours)+ ggtitle("UMAP of BM cells clustered") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")
DimPlot(onlyBM, reduction = "umap.harmony", group.by = "seurat_clusters", split.by = "Cell_Line_n")

saveplots(UMAPBMClust, "../BM Publication/", "UMAP BM by cluster", w = 1050)
svg("UMAP BM by cluster.svg")
UMAPBMClust
dev.off()
UMAPBMClust

VlnBMBMA <- VlnPlot(onlyBM, features = c("BM-Ascore1"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing", cols = Cluster_colours) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) +
stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + 
ggpubr::stat_compare_means(method = "anova", label.y = max(onlyBM@meta.data$`BM-Ascore1`, na.rm = TRUE) * 0.95)
VlnBMBMB <- VlnPlot(onlyBM, features = c("BM-Bscore1"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing", cols = Cluster_colours) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + 
ggpubr::stat_compare_means(method = "anova", label.y = max(onlyBM@meta.data$`BM-Bscore1`, na.rm = TRUE) * 0.95)
VlnBMBMdiff <- VlnPlot(onlyBM, features = c("BMdiff"), group.by = "seurat_clusters", pt.size = 0, sort = "increasing", cols = Cluster_colours) + geom_boxplot(fill = "white", alpha = 0.5, width = 0.5,outliers = F) + stat_summary(fun = mean, geom = "point", shape = 23, size = 2, fill = "white", color = "black") + ggpubr::stat_compare_means(method = "anova", label.y = max(onlyBM@meta.data$BMdiff, na.rm = TRUE) * 0.95)

VlnBM <- wrap_plots(VlnBMBMA, VlnBMBMB, VlnBMBMdiff, ncol = 3)

saveplots(VlnBM, "../BM Publication/", "Vlnplot BM scores by cluster", w = 2500)
svg("Vlnplot BM scores by cluster.svg", width = 15, height = 6)
VlnBM
dev.off()
VlnBM

#Adding BM-A/B identity to BM cells from cluster belonging
onlyBM$type <- ifelse(onlyBM$seurat_clusters == 1, "BM-A", ifelse(onlyBM$seurat_clusters %in% c(6, 8), "BM-B", "Other"))

#Plotting BM-A/B scores in BM cells (Dimplot and Barplot)
UMAPBMtype <- DimPlot(onlyBM, reduction = "umap.harmony", group.by = "type", cols = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Other" = "lightgrey"), pt.size = 0.8) + ggtitle("UMAP of BM cells") + theme(axis.line = element_line(color = "black"), axis.title = element_text(size = 15, color = "black"), axis.ticks = element_blank(), axis.text = element_blank(), panel.border = element_rect(color = "black", size = 1)) + ylab("UMAP_2") + xlab("UMAP_1")

saveplots(UMAPBMtype, "../BM Publication/", "UMAP BM by BM-A BM-B", w = 1050)
svg("UMAP BM by BM-A BM-B.svg")
UMAPBMtype
dev.off()
UMAPBMtype

cellLine <- c(rep(c("LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"), each = 2))
type <- c(rep(c("BM-A", "BM-B"), times = 3))
percentage <- c(c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-1"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-1")))), c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-2"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-2")))), c(length(WhichCells(onlyBM, expression = type == "BM-A" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-3")))), c(length(WhichCells(onlyBM, expression = type == "BM-B" & Cell_Line_n == "LU-NB-3"))/length(colnames(subset(onlyBM, Cell_Line_n == "LU-NB-3")))))
barplotData5 <- data.frame(cellLine, type, percentage)
BarplotBM2 <- ggplot(barplotData5, aes(fill=type, y=percentage, x=cellLine, size=8)) + 
  geom_bar(position = "dodge", stat = "identity", width = 0.9) + 
  ggtitle("Percentage of BM-A/BM-B Cells") +
  scale_fill_manual(values = c("BM-A" = "#FF7F7F", "BM-B" = "#990000")) +
  scale_x_discrete(limits = c("LU-NB-1_BM", "LU-NB-2_BM", "LU-NB-3_BM"), labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3")) +
  scale_y_continuous(breaks = seq(0, 0.50, by = 0.1), labels = scales::label_percent(), expand = expansion(0, c(0, 0.05))) +
  geom_text(aes(label = 100*round(percentage, 4)), 
            position = position_dodge(width = 0.8), vjust = -0.8, color =  "black", size = 3) +
  theme_minimal() +
  theme(
  axis.text.x = element_text(size = 15, hjust = 0.5, colour = c(PDX_colours[1], PDX_colours[2], PDX_colours[3])),
  axis.text.y = element_text(size = 10),
  text = element_text(size = 12, color = "black"))

BarplotBM2

saveplots(BarplotBM2, "../BM Publication/", "Barplot BM type in BM by cluster")
svg("Barplot BM type in BM by cluster.svg")
BarplotBM2
dev.off()

```

```{r short preparation for MAST}
onlyBMAB <- subset(onlyBM, type %in% c("BM-A", "BM-B"))

#Factoring grouping factors and removing empty levels
PTCells@meta.data <- droplevels(PTCells@meta.data)
PTCells$Cell_Line_n <- as.factor(PTCells$Cell_Line_n)
PTCells$Mouse_n <- as.factor(PTCells$Mouse_n)
onlyBM@meta.data <- droplevels(onlyBM@meta.data)
onlyBM$Cell_Line_n <- as.factor(onlyBM$Cell_Line_n)
onlyBM$Mouse_n <- as.factor(onlyBM$Mouse_n)
onlyBMAB@meta.data <- droplevels(onlyBMAB@meta.data)
onlyBMAB$Cell_Line_n <- as.factor(onlyBMAB$Cell_Line_n)
onlyBMAB$Mouse_n <- as.factor(onlyBMAB$Mouse_n)

PTCells$A_vs_rest <- ifelse(PTCells$BMLike == "BM-A Like", "BM-A Like", "Rest")
PTCells$B_vs_rest <- ifelse(PTCells$BMLike == "BM-B Like", "BM-B Like", "Rest")
PTCells$A_vs_rest <- as.factor(PTCells$A_vs_rest)
PTCells$B_vs_rest <- as.factor(PTCells$B_vs_rest)

onlyBM$A_vs_rest <- ifelse(onlyBM$type == "BM-A", "BM-A", "Rest")
onlyBM$B_vs_rest <- ifelse(onlyBM$type == "BM-B", "BM-B", "Rest")
onlyBM$Other_vs_AB <- ifelse(onlyBM$type == "Other", "Other", "BM-AB")
onlyBM$A_vs_rest <- as.factor(onlyBM$A_vs_rest)
onlyBM$B_vs_rest <- as.factor(onlyBM$B_vs_rest)
onlyBM$Other_vs_AB <- as.factor(onlyBM$Other_vs_AB)

onlyBMAB$A_vs_B <- ifelse(onlyBMAB$type == "BM-A", "BM-A", "BM-B")
onlyBMAB$A_vs_B <- as.factor(onlyBMAB$A_vs_B)

```


```{r MAST Between BM-A Like/BM-B Like PT cells (BM-A Like to non, BM-B like to none)}
  Idents(PTCells) <- "A_vs_rest"
# View percentage of cells expressing Genes
  PctExpressing_BMALike <- data.frame(rowMeans(GetAssayData(subset(x = PTCells, idents = "BM-A Like"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(A_vs_rest = "BM-A Like")
  PctExpressing_BMOther <- data.frame(rowMeans(GetAssayData(subset(x = PTCells, idents = "Rest"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(A_vs_rest = "Rest")
# Rename columns
  colnames(PctExpressing_BMALike) <- c("Gene","Percentage_Expressing","A_vs_rest")
  colnames(PctExpressing_BMOther) <- c("Gene","Percentage_Expressing","A_vs_rest")

# Bind
  PctExpressing <- rbind(PctExpressing_BMALike, PctExpressing_BMOther) %>% arrange(Gene)

# Create gene selection vector
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(PTCells) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(PTCells) 

#Preparing MAST
  Integrated_logTPM <- GetAssayData(PTCells, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
# Create the feature data (gene information)
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
# Extract cell metadata from the Seurat object
  cell_metadata <- PTCells@meta.data
# Add a unique identifier column for each cell (well key)
  cell_metadata$wellKey <- rownames(cell_metadata)
# Create a SingleCellAssay object using MAST::FromMatrix
  sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )
# Remove unnecessary R objects
  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))
  
#Running MAST
random_zlm_fit <- MAST::zlm(formula = ~ 1 + A_vs_rest + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)
#Changing and removing Cell_Line_n/Mouse_n due to errors ( Error : grouping factors must have > 1 sampled level and fixed-effect model matrix is rank deficient so dropping 1 column / coefficient). As Cell_Line_n only has 1 mouse after subsetting to PT only. And I think because type/BMLike was very correlated to Cell_Line_n

#Processing
  random_zlm_summaryA <- MAST::summary(random_zlm_fit, doLRT = "A_vs_restBM-A Like")
  random_summary_dataA <- random_zlm_summaryA$datatable
# Filter and merge the summary data for logFC and Hurdle components
  random_logFC_dataA <- random_summary_dataA[random_summary_dataA$contrast == "A_vs_restBM-A Like" & random_summary_dataA$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataA <- random_summary_dataA[random_summary_dataA$contrast == "A_vs_restBM-A Like" & random_summary_dataA$component == "H", 
                                  c(1,4)]
# Merge logFC and Hurdle results
  mast_random_hurdle_resultsA <- merge(random_logFC_dataA, random_hurdle_dataA, by = "primerid")
# Remove any rows with missing data
  mast_analysis_resultsA <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsA))
# Organise in descending order and add Qvalue
  mast_analysis_resultsA <- mast_analysis_resultsA %>% 
    mutate(qvalue = qvalue(mast_analysis_resultsA$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))
  
saveRDS(mast_analysis_resultsA, "../BM Publication/MAST_BMALikevsOther.rds")
```

```{r MAST BM-B like against rest}
#Same for BM-B Like vs Other
  Idents(PTCells) <- "B_vs_rest"
  PctExpressing_BMBLike <- data.frame(rowMeans(GetAssayData(subset(x = PTCells, idents = "BM-B Like"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(B_vs_rest = "BM-B Like")
  PctExpressing_BMOther <- data.frame(rowMeans(GetAssayData(subset(x = PTCells, idents = "Rest"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(B_vs_rest = "Rest")
  colnames(PctExpressing_BMBLike) <- c("Gene","Percentage_Expressing","B_vs_rest")
  colnames(PctExpressing_BMOther) <- c("Gene","Percentage_Expressing","B_vs_rest")
  PctExpressing <- rbind(PctExpressing_BMBLike, PctExpressing_BMOther) %>% arrange(Gene)
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(PTCells) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(PTCells) 
  Integrated_logTPM <- GetAssayData(PTCells, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
  cell_metadata <- PTCells@meta.data
  cell_metadata$wellKey <- rownames(cell_metadata)

  sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )
  
  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))
  
random_zlm_fit <- MAST::zlm(formula = ~ 1 + B_vs_rest + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)

  random_zlm_summaryB <- MAST::summary(random_zlm_fit, doLRT = "B_vs_restBM-B Like")
  random_summary_dataB <- random_zlm_summaryB$datatable
  random_logFC_dataB <- random_summary_dataB[random_summary_dataB$contrast == "B_vs_restBM-B Like" & random_summary_dataB$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataB <- random_summary_dataB[random_summary_dataB$contrast == "B_vs_restBM-B Like" & random_summary_dataB$component == "H", 
                                  c(1,4)]
  mast_random_hurdle_resultsB <- merge(random_logFC_dataB, random_hurdle_dataB, by = "primerid")
  mast_analysis_resultsB <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsB))
  mast_analysis_resultsB <- mast_analysis_resultsB %>% 
    mutate(qvalue = qvalue(mast_analysis_resultsB$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))

saveRDS(mast_analysis_resultsB, "../BM Publication/MAST_BMBLikevsOther.rds")

# Q: Explain the code for the Mast analysis in detail, including the rationale for each step and how the data is being processed
# A: The code is performing a differential expression analysis using the MAST package to compare gene expression between BM-A Like and Other PT cells. The steps are as follows:
# 1. The code first sets the identities of the PTCells object to "BMLike", which categorizes the cells into BM-A Like, BM-B Like, and Other based on their scores.
# 2. It procedes to calculate the percentage of cells expressing each gene in the BM-A Like, BM-B Like, and Other groups. This is done by checking how many cells have non-zero counts for each gene and dividing by the total number of cells in that group.
# 3. Then it creates a selection vector for genes that are expressed in at least 5% of the cells in any of the groups. This is a common step to filter out genes that are not expressed in enough cells to be informative.
# 4. The code then subsets the log-transformed TPM data to include only the genes
# 5. Next, it creates a SingleCellAssay object using the MAST::FromMatrix function, which takes the expression data, cell metadata, and gene metadata. This object is required for running the MAST analysis.
# 6. The code then fits a linear mixed model using MAST::zlm, with the formula specifying that gene expression is modeled as a function of the BMLike group, the number of features (nFeature_RNA), and random effects for Cell_Line_n and Mouse_n. The method "glmer" indicates that it is using a generalized linear mixed model, and ebayes = FALSE means that it will not use empirical Bayes shrinkage.
# 7. After fitting the model, it summarizes the results using MAST::summary, specifying that it wants to perform a likelihood ratio test comparing BM-A Like to Other.. 
# 8. The summary results are then processed to extract the log fold change and p-values for the comparison of interest, and these are merged into a single data frame.
# 9. Finally, the results are cleaned up by removing any rows with missing data, and a q-value is calculated for multiple testing correction. The results are then arranged in descending order of the coefficient (log fold change) and saved as an RDS file for later use.
# Q: Why is it testing BM-A Like against others, how can it test BM-A Like against BM-B Like. Or BM-A Like to both BM-B Like and Other? 
# A: The code is currently set up to test BM-A Like against Other, which includes all cells that are not classified as BM-A Like. If you want to test BM-A Like against BM-B Like specifically, you would need to change the contrast in the MAST::summary function to "BMLikeBM-B Like". If you want to compare BM-A Like to both BM-B Like and Other, you would need to set up a different contrast that compares BM-A Like to the combined group of BM-B Like and Other, which might require creating a new variable in the metadata that groups BM-B Like and Other together before running the MAST analysis.
```

```{r Volcanoplots MAST results in PT}
#VolcPlot of results BM-A Like
mastResultsADF <- data.frame(Gene = mast_analysis_resultsA$primerid, Log2FC = mast_analysis_resultsA$coef, AdjPValue = mast_analysis_resultsA$`Pr(>Chisq)`, Significant = ifelse(mast_analysis_resultsA$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsA$coef > 0.25, "Upregulated", ifelse(mast_analysis_resultsA$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsA$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsADF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMastA <- ggplot(mastResultsADF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#6BAED6", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#FF7F7F")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "BM-A like PT cells against Not BM Like: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMastA, "../BM Publication/", "Volcanoplot Mast results BM-A Like")
svg("Volcanoplot Mast results BM-A Like.svg")
VolcanoplotMastA
dev.off()
VolcanoplotMastA

#Volcplot of results from BM-B Like
#VolcPlot of results BM-A Like
mastResultsBDF <- data.frame(Gene = mast_analysis_resultsB$primerid, Log2FC = mast_analysis_resultsB$coef, AdjPValue = mast_analysis_resultsB$`Pr(>Chisq)`, Significant = ifelse(mast_analysis_resultsB$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsB$coef > 0.25, "Upregulated", ifelse(mast_analysis_resultsB$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsB$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsBDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMastB <- ggplot(mastResultsBDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#6BAED6", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#990000")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "BM-B like PT cells against Not BM Like: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMastB, "../BM Publication/", "Volcanoplot Mast results BM-B Like")
svg("Volcanoplot Mast results BM-B Like.svg")
VolcanoplotMastB
dev.off()
VolcanoplotMastB
```

```{r Plotting Mast results in PT}
#Cutoff for selecting DEG BM-A Like
hist(mast_analysis_resultsA$`Pr(>Chisq)`)
UpGenesMastBMALike <- mast_analysis_resultsA$primerid[which(mast_analysis_resultsA$coef > 0.25 & mast_analysis_resultsA$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsA$qvalue < 0.05)]
DownGenesMastBMALike <- mast_analysis_resultsA$primerid[which(mast_analysis_resultsA$coef < 0.25 & mast_analysis_resultsA$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsA$qvalue < 0.05)]
SignGenesMastBMALike <- c(UpGenesMastBMALike, DownGenesMastBMALike)
#Cutoff for selecting DEG BM-B Like
hist(mast_analysis_resultsB$`Pr(>Chisq)`)
UpGenesMastBMBLike <- mast_analysis_resultsB$primerid[which(mast_analysis_resultsB$coef > 0.25 & mast_analysis_resultsB$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsB$qvalue < 0.05)]
DownGenesMastBMBLike <- mast_analysis_resultsB$primerid[which(mast_analysis_resultsB$coef < 0.25 & mast_analysis_resultsB$`Pr(>Chisq)` < 0.05 & mast_analysis_resultsB$qvalue < 0.05)]
SignGenesMastBMBLike <- c(UpGenesMastBMBLike, DownGenesMastBMBLike)

#Dotplot of results
DotplotBMA <- DotPlot(PTCells, features = UpGenesMastBMALike, group.by = "BMLike") + RotatedAxis()
DotplotBMB <- DotPlot(PTCells, features = UpGenesMastBMBLike, group.by = "BMLike") + RotatedAxis()
DotPlot(PTCells, features = SignGenesMastBMALike, group.by = "BMLike") + RotatedAxis()
DotPlot(PTCells, features = SignGenesMastBMBLike, group.by = "BMLike") + RotatedAxis()

saveplots(DotplotBMA, "../BM Publication/", "Dotplot BM-A Like DEG", w = 3000)
svg("Dotplot BM-A Like DEG.svg", width = 20)
DotplotBMA
dev.off()
saveplots(DotplotBMB, "../BM Publication/", "Dotplot BM-B Like DEG", w = 3000)
svg("Dotplot BM-B Like DEG.svg", width = 20)
DotplotBMB
dev.off()
```

```{r Heatmap BM-Like DEG}
#Heatmap of results (top 25 up and down genes for both comparisons in one heatmap, columns clustered, annotated for PDX)
HeatmapGeneList <- c(UpGenesMastBMALike[1:25], DownGenesMastBMALike[1:25], UpGenesMastBMBLike[1:25], DownGenesMastBMBLike[1:25])

HeatmapMatr <- GetAssayData(PTCells, assay = "SCT", layer = "scale.data")
HeatmapMatr <- HeatmapMatr[order(factor(rownames(HeatmapMatr), levels = HeatmapGeneList)), ]

HeatmapAnnotations <- HeatmapAnnotation(PDX = PTCells$Cell_Line_n, Profile = PTCells$BMLike, col = list(PDX = PDX_colours, Profile = c("BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000", "Other" = "lightgrey")), annotation_label = c("PDX", "Profile"), show_legend = FALSE)
HeatmapAnnotationRow <- rowAnnotation(Signature = ifelse(rownames(HeatmapMatr) %in% UpGenesMastBMALike, "BM-A Like Up DEG", ifelse(rownames(HeatmapMatr) %in% DownGenesMastBMALike, "BM-A Like Down DEG", ifelse(rownames(HeatmapMatr) %in% UpGenesMastBMBLike, "BM-B Like Up DEG", "BM-B Like Down DEG"))), show_legend = FALSE, col = list(Signature = c("BM-A Like Up DEG" = "#FF7F7F", "BM-B Like Up DEG" = "#990000", "BM-A Like Down DEG" = "#90D5FF", "BM-B Like Down DEG" = "#104581")), annotation_label = c(" "))

HMPT <- Heatmap(HeatmapMatr, name = "Heatmap", cluster_rows = FALSE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HeatmapAnnotations, rigth_annotation = HeatmapAnnotationRow, col = col_fun, use_raster = FALSE, column_title = "Heatmap BM-Like DE genes", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Lgnds
matrixLGND <- Legend(col_fun = col_fun, title = "Expression")
cellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
typeLGND <- Legend(labels = c("BM-A Like", "BM-B Like", "Other"), title = "Profile", legend_gp = gpar(fill = c("BM-A Like" = "#FF7F7F", "BM-B Like" = "#990000", "Other" = "lightgrey")))
GeneSignLGND <- Legend(labels = c("BM-A Like Up DEG", "BM-B Like Up DEG", "BM-A Like Down DEG", "BM-B Like Down DEG"), title = "Gene signature", legend_gp = gpar(fill = c("BM-A Like Up DEG" = "#FF7F7F", "BM-B Like Up DEG" = "#990000", "BM-A Like Down DEG" = "#90D5FF", "BM-B Like Down DEG" = "#104581")))
LGNDs3 <- packLegend(matrixLGND, cellLineLGND, typeLGND, GeneSignLGND)

HeatmapBMLikeDEG <- draw(HMPT, annotation_legend_list = LGNDs3)

png("Heatmap BM Like DEG.png", width = 3000, height = 3500, res = 300)
HeatmapBMLikeDEG
dev.off()
svg("Heatmap BM Like DEG.svg", width = 15, height = 10)
HeatmapBMLikeDEG
dev.off()
```

```{r GSEA from BM-A Like DE}
#Skapa lista med fold-change
gseaGeneList <- mast_analysis_resultsA$coef
names(gseaGeneList) <- mast_analysis_resultsA$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMALikeAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMALikeAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMALikeAll, "../BM Publication/", "Barplot GSEA KEGG BM-A Like", w = 2000)
svg("Barplot GSEA KEGG BM-A Like.svg", width = 20)
KEGGBMALikeAll
dev.off()
saveplots(GOBMALikeAll, "../BM Publication/", "Barplot GSEA GO BM-A Like", w = 2000)
svg("Barplot GSEA GO BM-A Like.svg", width = 20)
GOBMALikeAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBMALike10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBMALike10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBMALike10, "../BM Publication/", "Barplot GSEA KEGG top10 BM-A Like")
svg("Barplot GSEA KEGG top10 BM-A Like.svg")
KEGGBMALike10
dev.off()
saveplots(GOBMALike10, "../BM Publication/", "Barplot GSEA GO top10 BM-A Like", w = 1100)
svg("Barplot GSEA GO top10 BM-A Like.svg")
GOBMALike10
dev.off()
```

```{r GSEA from BM-B Like DE}
#Skapa lista med fold-change
gseaGeneList <- mast_analysis_resultsB$coef
names(gseaGeneList) <- mast_analysis_resultsB$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMBLikeAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMBLikeAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMBLikeAll, "../BM Publication/", "Barplot GSEA KEGG BM-B Like", w = 2000)
svg("Barplot GSEA KEGG BM-B Like.svg", width = 20)
KEGGBMBLikeAll
dev.off()
saveplots(GOBMBLikeAll, "../BM Publication/", "Barplot GSEA GO BM-B Like", w = 2000)
svg("Barplot GSEA GO BM-B Like.svg", width = 20)
GOBMBLikeAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBMBLike10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBMBLike10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBMBLike10, "../BM Publication/", "Barplot GSEA KEGG top10 BM-B Like")
svg("Barplot GSEA KEGG top10 BM-B Like.svg")
KEGGBMBLike10
dev.off()
saveplots(GOBMBLike10, "../BM Publication/", "Barplot GSEA GO top10 BM-B Like", w = 1100)
svg("Barplot GSEA GO top10 BM-B Like.svg")
GOBMBLike10
dev.off()
```


```{r MAST Between BM-A/BM-B BM cells (BM-A to BM-B), BM-A to all other, BM-B to all other and finaly other to BM-A and BM-B}
#MAST BM-A to BM-B
  Idents(onlyBMAB) <- "A_vs_B"
  PctExpressing_BMA <- data.frame(rowMeans(GetAssayData(subset(x = onlyBMAB, idents = "BM-A"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(type = "BM-A")
  PctExpressing_BMB <- data.frame(rowMeans(GetAssayData(subset(x = onlyBMAB, idents = "BM-B"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(type = "BM-B")
  colnames(PctExpressing_BMA) <- c("Gene","Percentage_Expressing","A_vs_B")
  colnames(PctExpressing_BMB) <- c("Gene","Percentage_Expressing","A_vs_B")
  PctExpressing <- rbind(PctExpressing_BMA,PctExpressing_BMB) %>% arrange(Gene)
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(onlyBMAB) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(onlyBMAB) 
  Integrated_logTPM <- GetAssayData(onlyBMAB, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
  cell_metadata <- onlyBMAB@meta.data
  cell_metadata$wellKey <- rownames(cell_metadata)

    sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )

  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))

random_zlm_fit <- MAST::zlm(formula = ~ 1 + A_vs_B + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)

  random_zlm_summaryBM <- MAST::summary(random_zlm_fit, doLRT = "A_vs_BBM-A")
  random_summary_dataBM <- random_zlm_summaryBM$datatable
  random_logFC_dataBM <- random_summary_dataBM[random_summary_dataBM$contrast == "A_vs_BBM-A" & random_summary_dataBM$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataBM <- random_summary_dataBM[random_summary_dataBM$contrast == "A_vs_BBM-A" & random_summary_dataBM$component == "H", 
                                  c(1,4)]
  mast_random_hurdle_resultsBM <- merge(random_logFC_dataBM, random_hurdle_dataBM, by = "primerid")
  mast_random_analysis_resultsBM <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsBM))
  mast_random_analysis_resultsBM <- mast_random_analysis_resultsBM %>% 
    mutate(qvalue = qvalue(mast_random_analysis_resultsBM$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))
  
saveRDS(mast_random_analysis_resultsBM, "../BM Publication/MAST_BMAvsBMB.rds")
```

```{r MAST BM-A to all other}
#Same for BM-B Like vs Other
  Idents(onlyBM) <- "A_vs_rest"
  PctExpressing_BMA <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "BM-A"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(A_vs_rest = "BM-A")
  PctExpressing_BMOther <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "Rest"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(A_vs_rest = "Rest")
  colnames(PctExpressing_BMA) <- c("Gene","Percentage_Expressing","A_vs_rest")
  colnames(PctExpressing_BMOther) <- c("Gene","Percentage_Expressing","A_vs_rest")
  PctExpressing <- rbind(PctExpressing_BMA, PctExpressing_BMOther) %>% arrange(Gene)
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(onlyBM) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(onlyBM) 
  Integrated_logTPM <- GetAssayData(onlyBM, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
  cell_metadata <- onlyBM@meta.data
  cell_metadata$wellKey <- rownames(cell_metadata)

  sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )
  
  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))
  
random_zlm_fit <- MAST::zlm(formula = ~ 1 + A_vs_rest + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)

  random_zlm_summaryBMA <- MAST::summary(random_zlm_fit, doLRT = "A_vs_restBM-A")
  random_summary_dataBMA <- random_zlm_summaryBMA$datatable
  random_logFC_dataBMA <- random_summary_dataBMA[random_summary_dataBMA$contrast == "A_vs_restBM-A" & random_summary_dataBMA$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataBMA <- random_summary_dataBMA[random_summary_dataBMA$contrast == "A_vs_restBM-A" & random_summary_dataBMA$component == "H", 
                                  c(1,4)]
  mast_random_hurdle_resultsBMA <- merge(random_logFC_dataBMA, random_hurdle_dataBMA, by = "primerid")
  mast_random_analysis_resultsBMA <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsBMA))
  mast_random_analysis_resultsBMA <- mast_random_analysis_resultsBMA %>% 
    mutate(qvalue = qvalue(mast_random_analysis_resultsBMA$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))
  
saveRDS(mast_random_analysis_resultsBMA, "../BM Publication/MAST_BMA.rds")
```

```{r MAST BM-B to all other}
#Same for BM-B Like vs Other
  Idents(onlyBM) <- "B_vs_rest"
  PctExpressing_BMB <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "BM-B"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(B_vs_rest = "BM-B")
  PctExpressing_BMOther <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "Rest"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(B_vs_rest = "Rest")
  colnames(PctExpressing_BMB) <- c("Gene","Percentage_Expressing","B_vs_rest")
  colnames(PctExpressing_BMOther) <- c("Gene","Percentage_Expressing","B_vs_rest")
  PctExpressing <- rbind(PctExpressing_BMA, PctExpressing_BMOther) %>% arrange(Gene)
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(onlyBM) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(onlyBM) 
  Integrated_logTPM <- GetAssayData(onlyBM, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
  cell_metadata <- onlyBM@meta.data
  cell_metadata$wellKey <- rownames(cell_metadata)

  sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )
  
  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))
  
random_zlm_fit <- MAST::zlm(formula = ~ 1 + B_vs_rest + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)

  random_zlm_summaryBMB <- MAST::summary(random_zlm_fit, doLRT = "B_vs_restBM-B")
  random_summary_dataBMB <- random_zlm_summaryBMB$datatable
  random_logFC_dataBMB <- random_summary_dataBMB[random_summary_dataBMB$contrast == "B_vs_restBM-B" & random_summary_dataBMB$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataBMB <- random_summary_dataBMB[random_summary_dataBMB$contrast == "B_vs_restBM-B" & random_summary_dataBMB$component == "H", 
                                  c(1,4)]
  mast_random_hurdle_resultsBMB <- merge(random_logFC_dataBMB, random_hurdle_dataBMB, by = "primerid")
  mast_random_analysis_resultsBMB <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsBMB))
  mast_random_analysis_resultsBMB <- mast_random_analysis_resultsBMB %>% 
    mutate(qvalue = qvalue(mast_random_analysis_resultsBMB$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))
  
saveRDS(mast_random_analysis_resultsBMB, "../BM Publication/MAST_BMB.rds")
```

```{r MAST other to BM-AB}
#Same for BM-B Like vs Other
  Idents(onlyBM) <- "Other_vs_AB"
  PctExpressing_BMOther <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "Other"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(Other_vs_AB = "Other")
  PctExpressing_BMAB <- data.frame(rowMeans(GetAssayData(subset(x = onlyBM, idents = "BM-AB"),assay = "RNA",slot = "counts") != 0) ) %>% 
    tibble::rownames_to_column(var = "Gene") %>% mutate(Other_vs_AB = "BM-AB")
  colnames(PctExpressing_BMOther) <- c("Gene","Percentage_Expressing","Other_vs_AB")
  colnames(PctExpressing_BMAB) <- c("Gene","Percentage_Expressing","Other_vs_AB")
  PctExpressing <- rbind(PctExpressing_BMOther, PctExpressing_BMAB) %>% arrange(Gene)
  passing_genes <- unique(PctExpressing$Gene[PctExpressing$Percentage_Expressing >= 0.05])
  Percent_gene_selection_vector <- rownames(onlyBM) %in% passing_genes
  names(Percent_gene_selection_vector) <- rownames(onlyBM) 
  Integrated_logTPM <- GetAssayData(onlyBM, assay = "RNA", layer = "data") 
  Integrated_logTPM_Subset <- Integrated_logTPM[Percent_gene_selection_vector,]
  gene_metadata <- data.frame(primerid  = rownames(Integrated_logTPM_Subset))
  cell_metadata <- onlyBM@meta.data
  cell_metadata$wellKey <- rownames(cell_metadata)

  sca_object <- MAST::FromMatrix(
      exprsArray = as.matrix(Integrated_logTPM_Subset),  
      cData = cell_metadata, 
      fData = gene_metadata,
      check_sanity = TRUE 
  )
  
  rm(list = c("Integrated_logTPM","Integrated_logTPM_Subset"))
  
random_zlm_fit <- MAST::zlm(formula = ~ 1 + Other_vs_AB + nFeature_RNA + (1 | Cell_Line_n/Mouse_n),
                                  sca_object, method = "glmer", ebayes = FALSE,parallel = TRUE)

  random_zlm_summaryBMO <- MAST::summary(random_zlm_fit, doLRT = "Other_vs_ABOther")
  random_summary_dataBMO <- random_zlm_summaryBMO$datatable
  random_logFC_dataBMO <- random_summary_dataBMO[random_summary_dataBMO$contrast == "Other_vs_ABOther" & random_summary_dataBMO$component == "logFC", 
                                 c(1,7,5,6,8)]
  random_hurdle_dataBMO <- random_summary_dataBMO[random_summary_dataBMO$contrast == "Other_vs_ABOther" & random_summary_dataBMO$component == "H", 
                                  c(1,4)]
  mast_random_hurdle_resultsBMO <- merge(random_logFC_dataBMO, random_hurdle_dataBMO, by = "primerid")
  mast_random_analysis_resultsBMO <- stats::na.omit(as.data.frame(mast_random_hurdle_resultsBMO))
  mast_random_analysis_resultsBMO <- mast_random_analysis_resultsBMO %>% 
    mutate(qvalue = qvalue(mast_random_analysis_resultsBMO$`Pr(>Chisq)`)$qvalues) %>% 
    arrange(desc(coef))
  
saveRDS(mast_random_analysis_resultsBMO, "../BM Publication/MAST_BMOther.rds")
```

```{r Plotting MAST results in BM (BM-A to BM-B)}
#VolcPlot of results
mastResultsDF <- data.frame(Gene = mast_random_analysis_resultsBM$primerid, Log2FC = mast_random_analysis_resultsBM$coef, AdjPValue = mast_random_analysis_resultsBM$`Pr(>Chisq)`, Significant = ifelse(mast_random_analysis_resultsBM$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBM$coef > 0.25, "Upregulated", ifelse(mast_random_analysis_resultsBM$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBM$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMast <- ggplot(mastResultsDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#990000", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#FF7F7F")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "BM-A against BM-B: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMast, "../BM Publication/", "Volcanoplot Mast results BM-A to BM-B")
svg("Volcanoplot Mast results BM-A to BM-B.svg")
VolcanoplotMast
dev.off()
VolcanoplotMast

#Cutoff for selecting DEG
hist(mast_random_analysis_resultsBM$`Pr(>Chisq)`)
BMAGenesMast <- mast_random_analysis_resultsBM$primerid[which(mast_random_analysis_resultsBM$coef > 0.25 & mast_random_analysis_resultsBM$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBM$qvalue < 0.05)]
BMBGenesMast <- mast_random_analysis_resultsBM$primerid[which(mast_random_analysis_resultsBM$coef < 0.25 & mast_random_analysis_resultsBM$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBM$qvalue < 0.05)]
SignGenesMastBM <- c(BMAGenesMast, BMBGenesMast)

#Dotplot of results
DotPlot(onlyBM, features = BMAGenesMast, group.by = "type") + RotatedAxis()
DotPlot(onlyBM, features = BMBGenesMast, group.by = "type") + RotatedAxis()
DotplotBMgenes <- DotPlot(onlyBM, features = SignGenesMastBM, group.by = "type") + RotatedAxis()

saveplots(DotplotBMgenes, "../BM Publication/", "Dotplot BM-A to BM-B DEG", w = 3000)
svg("Dotplot BM-A to BM-B DEG.svg", width = 20)
DotplotBMgenes
dev.off()
```

```{r Heatmap of BM-A to BM-B DEG}
#Heatmap of results (clustered columns with pdx and type annotation, top 40 BM-A and 40 BM-B genes)
HMBMGenes <- c(BMAGenesMast[1:40], BMBGenesMast[1:40])

HMMatr <- GetAssayData(onlyBM, assay = "SCT", layer = "scale.data")
HMMatr <- HMMatr[order(factor(rownames(HMMatr), levels = HMBMGenes)), ]

HMAnnotations <- HeatmapAnnotation(PDX = onlyBM$Cell_Line_n, Profile = onlyBM$type, col = list(PDX = PDX_colours, Profile = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Other" = "lightgrey")), annotation_label = c("PDX", "Profile"), show_legend = FALSE)
HMAnnotationRow <- rowAnnotation(Signature = ifelse(rownames(HMMatr) %in% BMAGenesMast, "BM-A DEG", "BM-B DEG"), show_legend = FALSE, col = list(Signature = c("BM-A DEG" = "#FF7F7F", "BM-B DEG" = "#990000")), annotation_label = c(" "))

HMBM <- Heatmap(HMMatr, name = "Heatmap", cluster_rows = FALSE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HMAnnotations, rigth_annotation = HMAnnotationRow, col = col_fun, use_raster = FALSE, column_title = "Heatmap BM-A/B DEG", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Lgnds
BMmatrixLGND <- Legend(col_fun = col_fun, title = "Expression")
BMcellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
BMtypeLGND <- Legend(labels = c("BM-A", "BM-B", "Other"), title = "Profile", legend_gp = gpar(fill = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Other" = "lightgrey")))
BMGeneSignLGND <- Legend(labels = c("BM-A DEG", "BM-B DEG"), title = "Gene signature", legend_gp = gpar(fill = c("BM-A DEG" = "#FF7F7F", "BM-B DEG" = "#990000")))
LGNDs4 <- packLegend(matrixLGND, cellLineLGND, typeLGND, GeneSignLGND)

HeatmapBMDEG <- draw(HMBM, annotation_legend_list = LGNDs4)

png("Heatmap BM-A/B DEG.png", width = 3000, height = 3500, res = 300)
HeatmapBMDEG
dev.off()
svg("Heatmap BM-A/B DEG.svg", width = 15, height = 10)
HeatmapBMDEG
dev.off()
```

```{r Plotting BMA to all other}
#VolcPlot of results
mastResultsDF <- data.frame(Gene = mast_random_analysis_resultsBMA$primerid, Log2FC = mast_random_analysis_resultsBMA$coef, AdjPValue = mast_random_analysis_resultsBMA$`Pr(>Chisq)`, Significant = ifelse(mast_random_analysis_resultsBMA$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMA$coef > 0.25, "Upregulated", ifelse(mast_random_analysis_resultsBMA$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMA$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMastBMA <- ggplot(mastResultsDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#990000", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#FF7F7F")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "BM-A to all other cells: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMastBMA, "../BM Publication/", "Volcanoplot Mast results BM-A to all other")
svg("Volcanoplot Mast results BM-A to all other.svg")
VolcanoplotMastBMA
dev.off()
VolcanoplotMastBMA

#Cutoff for selecting DEG
hist(mast_random_analysis_resultsBMA$`Pr(>Chisq)`)
BMAUpGenesMast <- mast_random_analysis_resultsBMA$primerid[which(mast_random_analysis_resultsBMA$coef > 0.25 & mast_random_analysis_resultsBMA$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMA$qvalue < 0.05)]
BMADownGenesMast <- mast_random_analysis_resultsBMA$primerid[which(mast_random_analysis_resultsBMA$coef < 0.25 & mast_random_analysis_resultsBMA$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMA$qvalue < 0.05)]
SignGenesMastBMA <- c(BMAUpGenesMast, BMADownGenesMast)

#Dotplot of results
DotPlot(onlyBM, features = BMAUpGenesMast, group.by = "type") + RotatedAxis()
DotPlot(onlyBM, features = BMADownGenesMast, group.by = "type") + RotatedAxis()
DotplotBMAgenes <- DotPlot(onlyBM, features = SignGenesMastBMA, group.by = "type") + RotatedAxis()

saveplots(DotplotBMAgenes, "../BM Publication/", "Dotplot BM-A to all other", w = 3000)
svg("Dotplot BM-A to all other.svg", width = 20)
DotplotBMAgenes
dev.off()
```

```{r Plotting BMB to all other}
#VolcPlot of results
mastResultsDF <- data.frame(Gene = mast_random_analysis_resultsBMB$primerid, Log2FC = mast_random_analysis_resultsBMB$coef, AdjPValue = mast_random_analysis_resultsBMB$`Pr(>Chisq)`, Significant = ifelse(mast_random_analysis_resultsBMB$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMB$coef > 0.25, "Upregulated", ifelse(mast_random_analysis_resultsBMB$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMB$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMastBMB <- ggplot(mastResultsDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#990000", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#FF7F7F")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "BM-B to all other BM cells: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMastBMB, "../BM Publication/", "Volcanoplot Mast results BM-B to all other")
svg("Volcanoplot Mast results BM-B to all other.svg")
VolcanoplotMastBMB
dev.off()
VolcanoplotMastBMB

#Cutoff for selecting DEG
hist(mast_random_analysis_resultsBMB$`Pr(>Chisq)`)
BMBUpGenesMast <- mast_random_analysis_resultsBMB$primerid[which(mast_random_analysis_resultsBMB$coef > 0.25 & mast_random_analysis_resultsBMB$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMB$qvalue < 0.05)]
BMBDownGenesMast <- mast_random_analysis_resultsBMB$primerid[which(mast_random_analysis_resultsBMB$coef < 0.25 & mast_random_analysis_resultsBMB$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMB$qvalue < 0.05)]
SignGenesMastBMB <- c(BMBUpGenesMast, BMBDownGenesMast)

#Dotplot of results
DotPlot(onlyBM, features = BMBUpGenesMast, group.by = "type") + RotatedAxis()
DotPlot(onlyBM, features = BMBDownGenesMast, group.by = "type") + RotatedAxis()
DotplotBMBgenes <- DotPlot(onlyBM, features = SignGenesMastBMB, group.by = "type") + RotatedAxis()

saveplots(DotplotBMBgenes, "../BM Publication/", "Dotplot BM-B to all other", w = 3000)
svg("Dotplot BM-B to all other.svg", width = 20)
DotplotBMBgenes
dev.off()
```

```{r Plotting BMOther to BM-A+BM-B}
#VolcPlot of results
mastResultsDF <- data.frame(Gene = mast_random_analysis_resultsBMO$primerid, Log2FC = mast_random_analysis_resultsBMO$coef, AdjPValue = mast_random_analysis_resultsBMO$`Pr(>Chisq)`, Significant = ifelse(mast_random_analysis_resultsBMO$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMO$coef > 0.25, "Upregulated", ifelse(mast_random_analysis_resultsBMO$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMO$coef < -0.25, "Downregulated", "Not Significant")))

top_genes <- mastResultsDF %>%
  filter(Log2FC > 0.25 | Log2FC < -0.25) %>%
  arrange(AdjPValue) %>%
  dplyr::slice(1:40)

VolcanoplotMastBMO <- ggplot(mastResultsDF, aes(x = Log2FC, y = -log10(AdjPValue), color = Significant)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous(breaks = seq(0, 1000, by = 100), expand = expansion(0, c(0, 100))) +
  scale_color_manual(values = c("Downregulated" = "#990000", #"#00AFBB"
                                "Not significant" = "grey",
                                "Upregulated" = "#FF7F7F")) +
  geom_vline(xintercept = c(-0.25, 0.25), linetype = "dashed") +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed") +
  geom_point(size = 1) +
  geom_text_repel(data = top_genes, aes(label = Gene), size = 2, max.overlaps = 20) +
  theme_minimal() +
  labs(title = "Other against BM-A and BM-B: Differentially Expressed Genes",
       x = "Average ln Fold Change",
       y = "-log10 P-value")

saveplots(VolcanoplotMastBMO, "../BM Publication/", "Volcanoplot Mast results Other to BM-A and BM-B")
svg("Volcanoplot Mast results other to BM-A and BM-B.svg")
VolcanoplotMastBMO
dev.off()
VolcanoplotMastBMO

#Cutoff for selecting DEG
hist(mast_random_analysis_resultsBMO$`Pr(>Chisq)`)
BMOUpGenesMast <- mast_random_analysis_resultsBMO$primerid[which(mast_random_analysis_resultsBMO$coef > 0.25 & mast_random_analysis_resultsBMO$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMO$qvalue < 0.05)]
BMODownGenesMast <- mast_random_analysis_resultsBMO$primerid[which(mast_random_analysis_resultsBMO$coef < 0.25 & mast_random_analysis_resultsBMO$`Pr(>Chisq)` < 0.05 & mast_random_analysis_resultsBMO$qvalue < 0.05)]
SignGenesMastBMO <- c(BMOUpGenesMast, BMODownGenesMast)

#Dotplot of results
DotPlot(onlyBM, features = BMOUpGenesMast, group.by = "type") + RotatedAxis()
DotPlot(onlyBM, features = BMODownGenesMast, group.by = "type") + RotatedAxis()
DotplotBMAgenes <- DotPlot(onlyBM, features = SignGenesMastBMO, group.by = "type") + RotatedAxis()

saveplots(DotplotBMOgenes, "../BM Publication/", "Dotplot BM Other to BM-A and B", w = 3000)
svg("Dotplot BM Other to BM-A and B.svg", width = 20)
DotplotBMOgenes
dev.off()
```

```{r Combined Heatmap of BM-A, BM-B and BM-Other}
#Heatmap of results (clustered columns with pdx and type annotation, top 40 BM-A and 40 BM-B genes)
HMBMGenes2 <- c(BMAUpGenesMast[1:20], BMBUpGenesMast[1:20], BMOUpGenesMast[1:20])

HMMatr <- GetAssayData(onlyBM, assay = "SCT", layer = "scale.data")
HMMatr <- HMMatr[order(factor(rownames(HMMatr), levels = HMBMGenes2)), ]

HMAnnotations <- HeatmapAnnotation(PDX = onlyBM$Cell_Line_n, Profile = onlyBM$type, col = list(PDX = PDX_colours, Profile = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Other" = "lightgrey")), annotation_label = c("PDX", "Profile"), show_legend = FALSE)
HMAnnotationRow <- rowAnnotation(Signature = ifelse(rownames(HMMatr) %in% BMAUpGenesMast, "BM-A DEG", ifelse(rownames(HMMatr) %in% BMBUpGenesMast, "BM-B DEG", "Other DEG")), show_legend = FALSE, col = list(Signature = c("BM-A DEG" = "#FF7F7F", "BM-B DEG" = "#990000", "Other DEG" = "lightgrey")), annotation_label = c(" "))

HMBM2 <- Heatmap(HMMatr, name = "Heatmap", cluster_rows = FALSE, cluster_columns = TRUE, show_column_dend = TRUE, show_column_names = FALSE, show_row_dend = FALSE, top_annotation = HMAnnotations, rigth_annotation = HMAnnotationRow, col = col_fun, use_raster = FALSE, column_title = "Heatmap BM type DEG", show_heatmap_legend = FALSE, row_names_gp = gpar(fontsize = 6))

#Lgnds
BMmatrixLGND <- Legend(col_fun = col_fun, title = "Expression")
BMcellLineLGND <- Legend(labels = c("LU-NB-1", "LU-NB-2", "LU-NB-3"), title = "PDX", legend_gp = gpar(fill = PDX_colours))
BMtypeLGND <- Legend(labels = c("BM-A", "BM-B", "Other"), title = "Profile", legend_gp = gpar(fill = c("BM-A" = "#FF7F7F", "BM-B" = "#990000", "Other" = "lightgrey")))
BMGeneSignLGND2 <- Legend(labels = c("BM-A DEG", "BM-B DEG", "Other DEG"), title = "Gene signature", legend_gp = gpar(fill = c("BM-A DEG" = "#FF7F7F", "BM-B DEG" = "#990000", "Other DEG" = "lightgrey")))
LGNDs5 <- packLegend(matrixLGND, cellLineLGND, typeLGND, GeneSignLGND2)

HeatmapBMDEG2 <- draw(HMBM2, annotation_legend_list = LGNDs5)

png("Heatmap BM combined DEG.png", width = 3000, height = 3500, res = 300)
HeatmapBMDEG2
dev.off()
svg("Heatmap BM combined DEG.svg", width = 15, height = 10)
HeatmapBMDEG2
dev.off()
```


```{r gsea from results BM}
#Skapa lista med fold-change
gseaGeneList <- mast_random_analysis_resultsBM$coef
names(gseaGeneList) <- mast_analysis_results$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMAll, "../BM Publication/", "Barplot GSEA KEGG BM-A/B", w = 2000)
svg("Barplot GSEA KEGG BM-A/B.svg", width = 20)
KEGGBMAll
dev.off()
saveplots(GOBMAll, "../BM Publication/", "Barplot GSEA GO BM-A/B", w = 2000)
svg("Barplot GSEA GO BM-A/B.svg", width = 20)
GOBMAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBM10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBM10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBM10, "../BM Publication/", "Barplot GSEA KEGG top10 BM-A/B")
svg("Barplot GSEA KEGG top10 BM-A/B.svg")
KEGGBM10
dev.off()
saveplots(GOBM10, "../BM Publication/", "Barplot GSEA GO top10 BM-A/B", w = 1100)
svg("Barplot GSEA GO top10 BM-A/B.svg")
GOBM10
dev.off()
```

```{r GSEA from BM-A to all other}
#Skapa lista med fold-change
gseaGeneList <- mast_random_analysis_resultsBMA$coef
names(gseaGeneList) <- mast_analysis_results$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMAAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMAAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMAAll, "../BM Publication/", "Barplot GSEA KEGG BM-A to all other", w = 2000)
svg("Barplot GSEA KEGG BM-A to all other.svg", width = 20)
KEGGBMAAll
dev.off()
saveplots(GOBMAAll, "../BM Publication/", "Barplot GSEA GO BM-A to all other", w = 2000)
svg("Barplot GSEA GO BM-A to all other.svg", width = 20)
GOBMAAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBMA10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBMA10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBMA10, "../BM Publication/", "Barplot GSEA KEGG top10 BM-A to all other")
svg("Barplot GSEA KEGG top10 BM-A to all other.svg")
KEGGBMA10
dev.off()
saveplots(GOBMA10, "../BM Publication/", "Barplot GSEA GO top10 BM-A to all other", w = 1100)
svg("Barplot GSEA GO top10 BM-A to all other.svg")
GOBMA10
dev.off()
```

```{r GSEA from BM-B to all other}
#Skapa lista med fold-change
gseaGeneList <- mast_random_analysis_resultsBMB$coef
names(gseaGeneList) <- mast_analysis_results$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMBAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMBAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMBAll, "../BM Publication/", "Barplot GSEA KEGG BM-B to all other", w = 2000)
svg("Barplot GSEA KEGG BM-B to all other.svg", width = 20)
KEGGBMBAll
dev.off()
saveplots(GOBMBAll, "../BM Publication/", "Barplot GSEA GO BM-B to all other", w = 2000)
svg("Barplot GSEA GO BM-B to all other.svg", width = 20)
GOBMBAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBMB10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBMB10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBMB10, "../BM Publication/", "Barplot GSEA KEGG top10 BM-B to all other")
svg("Barplot GSEA KEGG top10 BM-B to all other.svg")
KEGGBMB10
dev.off()
saveplots(GOBMB10, "../BM Publication/", "Barplot GSEA GO top10 BM-B to all other", w = 1100)
svg("Barplot GSEA GO top10 BM-B to all other.svg")
GOBMB10
dev.off()
```

```{r GSEA from BM-O to BM-A and B}
#Skapa lista med fold-change
gseaGeneList <- mast_random_analysis_resultsBMO$coef
names(gseaGeneList) <- mast_analysis_results$primerid
GeneNameDF <- bitr(names(gseaGeneList), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db) #översätter till entrez

gseaGeneList <- gseaGeneList[GeneNameDF$SYMBOL]
names(gseaGeneList) <- GeneNameDF$ENTREZID
gseaGeneList <- sort(gseaGeneList, decreasing = TRUE)

#Running GSEA
KEGGResult <- gseKEGG(geneList = gseaGeneList, organism = "hsa", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- gseGO(geneList = gseaGeneList, OrgDb = org.Hs.eg.db, keyType = "ENTREZID", ont = "BP", pvalueCutoff = 0.05, verbose = FALSE)
GOResult <- simplify(GOResult, cutoff = 0.7, by = "p.adjust", select_fun = min, measure = "Wang")

#Preparing/setting order
DFKEGGResult <- KEGGResult@result
DFKEGGResult <- DFKEGGResult[DFKEGGResult$p.adjust < 0.05, ]
DFKEGGResult <- head(DFKEGGResult[order(DFKEGGResult$p.adjust), ], 100)
DFKEGGResult <- DFKEGGResult[order(-DFKEGGResult$p.adjust), ]
UpKegg <- DFKEGGResult$Description[DFKEGGResult$NES > 0]
DFKEGGResult <- DFKEGGResult[order(DFKEGGResult$p.adjust), ]
DownKegg <- DFKEGGResult$Description[DFKEGGResult$NES < 0]
order <- c(DownKegg, UpKegg)
DFKEGGResult$Description <- factor(DFKEGGResult$Description, levels = order)

#Plotting All KEGG
KEGGBMOAll <- ggplot(DFKEGGResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

#Preparing/setting order
DFGOResult <- GOResult@result
DFGOResult <- DFGOResult[DFGOResult$p.adjust < 0.05, ]
DFGOResult <- head(DFGOResult[order(DFGOResult$p.adjust), ], 100)
DFGOResult <- DFGOResult[order(-DFGOResult$p.adjust), ]
UpGO <- DFGOResult$Description[DFGOResult$NES > 0]
DFGOResult <- DFGOResult[order(DFGOResult$p.adjust), ]
DownGO <- DFGOResult$Description[DFGOResult$NES < 0]
order <- c(DownGO, UpGO)
DFGOResult$Description <- factor(DFGOResult$Description, levels = order)

#Plotting All GO
GOBMOAll <- ggplot(DFGOResult, aes(x = Description, y = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = NULL, y = "-log 10 Adjusted P-value", title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold"), 
        axis.text.x = element_text(angle = 60, hjust = 1)
  )

saveplots(KEGGBMOAll, "../BM Publication/", "Barplot GSEA KEGG other to BM-A and B", w = 2000)
svg("Barplot GSEA KEGG other to BM-A and B.svg", width = 20)
KEGGBMOAll
dev.off()
saveplots(GOBMOAll, "../BM Publication/", "Barplot GSEA GO other to BM-A and B", w = 2000)
svg("Barplot GSEA GO other to BM-A and B.svg", width = 20)
GOBMOAll
dev.off()

#Selecting top 10
DFKEGG10 <- rbind(head(DFKEGGResult, n = 10), tail(DFKEGGResult, n = 10))
DFGO10 <- rbind(head(DFGOResult, n = 10), tail(DFGOResult, n = 10))

#Plotting top 10
KEGGBMO10 <- ggplot(DFKEGG10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "KEGG GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )
GOBMO10 <- ggplot(DFGO10, aes(x = ifelse(NES < 0, log(p.adjust), -log(p.adjust)), y = Description, fill = NES)) +
  geom_col(width = 0.8) +
  labs(x = "-log 10 Adjusted P-value", y = NULL, title = "GO GSEA") +
  scale_fill_gradient(low  = "blue", high = "red", name = "NES") +
  theme_minimal(base_size = 12) +
  theme(plot.title = element_text(face = "bold")
  )

saveplots(KEGGBMO10, "../BM Publication/", "Barplot GSEA KEGG top10 other to BM-A and B")
svg("Barplot GSEA KEGG top10 other to BM-A and B.svg")
KEGGBMO10
dev.off()
saveplots(GOBMA10, "../BM Publication/", "Barplot GSEA GO top10 other to BM-A and B", w = 1100)
svg("Barplot GSEA GO top10 other to BM-A and B.svg")
GOBMO10
dev.off()
```


```{r Comparing between different DEG lists}
#Venn diagram
venn.plot <- venn.diagram(
  x = list("BM-A original" = BMAGenes, "BM-B original" = BMBgenes, "BM-A DEG" = BMAGenesMast, "BM-B DEG" = BMBGenesMast, "BM-A Like DEG" = UpGenesMastBMALike, "BM-B Like DEG" = UpGenesMastBMBLike),
  category.names = c("BM-A original", "BM-B original", "BM-A DEG", "BM-B DEG", "BM-A Like DEG", "BM-B Like DEG"),
  filename = NULL,
  fill = c("#F4C40FFF", "#FE9B00FF", "#D8443CFF", "#9B3441FF", "#DE597CFF", "#E87B89FF"),
  alpha = 0.6,
  col = "black",
  lwd = 2,
  cex = 2,
  fontface = "bold",
  cat.fontface = "bold",
  cat.col = c("#F4C40FFF", "#FE9B00FF", "#D8443CFF", "#9B3441FF", "#DE597CFF", "#E87B89FF"),
  margin = 0.1,
  output=TRUE
)
venn.plot

#Venn diagram
venn.plot2 <- venn.diagram(
  x = list("BM-A original" = BMAGenes, "BM-B original" = BMBgenes, "BM-A DEG" = BMAGenesMast, "BM-B DEG" = BMBGenesMast, "BM-A Like DEG" = UpGenesMastBMALike, "BM-B Like DEG" = UpGenesMastBMBLike, "BM-A DEG 2" = BMAUpGenesMast, "BM-B DEG 2" = BMBUpGenesMast, "BM Other DEG" = BMOUpGenesMast),
  category.names = c("BM-A original", "BM-B original", "BM-A DEG", "BM-B DEG", "BM-A Like DEG", "BM-B Like DEG", "BM-A DEG 2", "BM-B DEG 2", "BM Other DEG"),
  filename = NULL,
  fill = c("#F4C40FFF", "#FE9B00FF", "#D8443CFF", "#9B3441FF", "#DE597CFF", "#E87B89FF", "#E6A2A6FF", "#AA7AA1FF", "#9F5691FF"),
  alpha = 0.6,
  col = "black",
  lwd = 2,
  cex = 2,
  fontface = "bold",
  cat.fontface = "bold",
  cat.col = c("#F4C40FFF", "#FE9B00FF", "#D8443CFF", "#9B3441FF", "#DE597CFF", "#E87B89FF", "#E6A2A6FF", "#AA7AA1FF", "#9F5691FF"),
  margin = 0.1,
  output=TRUE
)
venn.plot2
```

```{Monocle in all cells (PT as startpoint and BM as endpoint)}
#Creatning object
DefaultAssay(IntegratedObject) <- "RNA"
cds <- SeuratWrappers::as.cell_data_set(IntegratedObject)

#Checking
class(cds)
reducedDims(cds)
names(colData(cds))

#Transfering umap
reducedDims(cds)$UMAP <- Embeddings(IntegratedObject, "umap.harmony")
reducedDims(cds)

#Transfering clusters
clusters <- IntegratedObject$seurat_clusters
names(clusters) <- colnames(IntegratedObject)
cds@clusters$UMAP$clusters <- clusters

#Setting 1 partition?
#partitions <- factor(rep(1, ncol(cds)))
#names(partitions) <- colnames(cds)
#cds@clusters$UMAP$partitions <- partitions

plot_cells(cds, show_trajectory_graph = FALSE, color_cells_by = "seurat_clusters", label_groups_by_cluster = TRUE, label_leaves = TRUE, label_branch_points = TRUE)
plot_cells(cds, show_trajectory_graph = FALSE, color_cells_by = "partition")

#For selecting starting cluster
#root_cells <- colnames(cds)[
#  cds@clusters$UMAP$clusters == "?3?"
#]

cds <- learn_graph(cds, use_partition = FALSE)
cds <- order_cells(cds) #Picking startpoint (possible to pick endpoint and reverse, har for 2 endpoints?)

plot_cells(cds, color_cells_by = "pseudotime")

#Findning DEG among path
cds_pt_res <- graph_test(cds, neighbor_graph = "principal_graph", cores = 4)
cds_pt_res <- na.omit(cds_pt_res)
cds_pt_res <- cds_pt_res[cds_pt_res$p_value < 0.05 & cds_pt_res$status == "OK", ]
cds_pt_res[order(-cds_pt_res$morans_test_statistic), ]
cds_pt_res

#Plotting interesting genes
plot_cells(cds, genes = c("Gene1", "Gene2", "Gene3", "Gene4"))

saveRDS(cds, "Monocle PT.rds")
saveRDS(cds, "Monocle PT genes.rds")
```

```{Monocle in only BM cells (BM-A and BM-B as startpoints)}
#Creatning object
DefaultAssay(onlyBM) <- "RNA"
cdsBM <- SeuratWrappers::as.cell_data_set(onlyBM)

#Checking
class(cdsBM)
reducedDims(cdsBM)
names(colData(cdsBM))

#Transfering umap
reducedDims(cdsBM)$UMAP <- Embeddings(onlyBM, "umap.harmony")
reducedDims(cdsBM)

#Transfering clusters
clusters <- onlyBM$seurat_clusters
names(clusters) <- colnames(onlyBM)
cdsBM@clusters$UMAP$clusters <- clusters

#Setting 1 partition?
#partitions <- factor(rep(1, ncol(cdsBM)))
#names(partitions) <- colnames(cdsBM)
#cdsBM@clusters$UMAP$partitions <- partitions

plot_cells(cdsBM, show_trajectory_graph = FALSE, color_cells_by = "seurat_clusters", label_groups_by_cluster = TRUE, label_leaves = TRUE, label_branch_points = TRUE)
plot_cells(cdsBM, show_trajectory_graph = FALSE, color_cells_by = "partition")

#For selecting starting cluster
#root_cells <- colnames(cds)[
#  cds@clusters$UMAP$clusters == "?3?"
#]

cdsBM <- learn_graph(cdsBM, use_partition = FALSE)
cdsBM <- order_cells(cdsBM) #Picking startpoint (possible to pick endpoint and reverse, har for 2 endpoints?)

plot_cells(cdsBM, color_cells_by = "pseudotime")

#Findning DEG among path
cds_pt_resBM <- graph_test(cdsBM, neighbor_graph = "principal_graph", cores = 4)
cds_pt_resBM <- na.omit(cds_pt_resBM)
cds_pt_resBM <- cds_pt_resBM[cds_pt_resBM$p_value < 0.05 & cds_pt_resBM$status == "OK", ]
cds_pt_resBM[order(-cds_pt_resBM$morans_test_statistic), ]
cds_pt_resBM

#Plotting interesting genes
plot_cells(cdsBM, genes = c("Gene1", "Gene2", "Gene3", "Gene4"))

saveRDS(cds, "Monocle BM.rds")
saveRDS(cds, "Monocle BM genes.rds")
```

